import {mkdir,readFile,rename,stat,unlink,writeFile} from 'node:fs/promises';
import {basename,join} from 'node:path';
import {randomUUID} from 'node:crypto';

const RATIOS={square:[1024,1024],portrait:[896,1152],landscape:[1152,896],wide:[1280,720],tall:[720,1280]};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

export class ImageService {
  constructor(root,{runnerUrl=process.env.SEEK_IMAGE_URL||'http://127.0.0.1:18810',routerUrl=process.env.SEEK_MODEL_URL||'http://127.0.0.1:18798',canStart=()=>true,log=console}={}){this.root=join(root,'images');this.output=join(this.root,'outputs');this.store=join(this.root,'images.json');this.runnerUrl=runnerUrl.replace(/\/$/,'');this.routerUrl=routerUrl.replace(/\/$/,'');this.canStart=canStart;this.log=log;this.data={version:1,items:[]};this.active=null;this.serial=Promise.resolve();}
  async init(){await mkdir(this.output,{recursive:true});try{this.data={...this.data,...JSON.parse(await readFile(this.store,'utf8'))};}catch(e){if(e.code!=='ENOENT')this.log.warn('Image history could not be opened: '+e.message);}if(!Array.isArray(this.data.items))this.data.items=[];return this;}
  async save(){const tmp=this.store+'.tmp';await writeFile(tmp,JSON.stringify(this.data,null,2));await rename(tmp,this.store);}
  async runner(path,body){const response=await fetch(this.runnerUrl+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(body?20*60_000:5000)});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||`Image runner returned ${response.status}.`);return value;}
  async runnerStatus(){try{return await this.runner('/health');}catch(e){return {available:false,ready:false,error:'Qwen Image runner is not running. Run the one-time local setup from the Images screen.',detail:e.message};}}
  async routerModels(){const response=await fetch(this.routerUrl+'/v1/models',{signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('The local language-model router is unavailable.');const value=await response.json();return (value.data||[]).filter(m=>m.status?.value==='loaded').map(m=>m.id);}
  async waitRouter(model,wanted,timeout=90_000){const until=Date.now()+timeout;while(Date.now()<until){const response=await fetch(this.routerUrl+'/v1/models',{signal:AbortSignal.timeout(5000)});if(response.ok){const data=await response.json(),row=(data.data||[]).find(m=>m.id===model);if(row?.status?.value===wanted)return;}await sleep(500);}throw new Error(`The local language model did not ${wanted} in time.`);}
  async setRouter(action,model){const response=await fetch(this.routerUrl+'/models/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model}),signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`Could not ${action} the local language model.`);}
  public(item){return {...item,url:'/qwen-image/api/file?id='+encodeURIComponent(item.id)};}
  history(){return {active:this.active?{id:this.active.id,prompt:this.active.prompt,startedAt:this.active.startedAt}:null,items:this.data.items.map(x=>this.public(x)),ratios:Object.keys(RATIOS)};}
  async status(){const runner=await this.runnerStatus();return {...runner,active:this.active?{id:this.active.id,prompt:this.active.prompt,startedAt:this.active.startedAt}:null,history:this.data.items.length,ratios:Object.keys(RATIOS),model:'Qwen/Qwen-Image-2.1'};}
  file(id){const item=this.data.items.find(row=>row.id===id);if(!item)throw new Error('Image not found.');return join(this.output,item.file);}
  async generate(request){if(typeof request?.prompt!=='string'||!request.prompt.trim()||request.prompt.trim().length>6000)throw new Error('Describe the image in 1–6000 characters.');const ratio=RATIOS[request?.ratio]?request.ratio:'square',id=randomUUID(),prompt=request.prompt.trim(),transparent=!!request.transparent,steps=Math.max(20,Math.min(40,Number(request.steps)||30));const task=async()=>{if(!(await this.canStart()))throw new Error('Seek is using the language model right now. Wait for the current reply or task to finish, then generate the image.');const runner=await this.runnerStatus();if(!runner.available||!runner.ready)throw new Error(runner.error||'Qwen Image is not installed yet. Use Set up local model in Images.');const size=RATIOS[ratio];this.active={id,prompt,startedAt:Date.now()};let loaded=[];try{loaded=await this.routerModels();for(const model of loaded){await this.setRouter('unload',model);await this.waitRouter(model,'unloaded');}const result=await this.runner('/generate',{id,prompt,transparent,steps,width:size[0],height:size[1],outputDir:this.output});const file=basename(String(result.file||''));if(!file||!/^[-_a-zA-Z0-9]+\.png$/i.test(file))throw new Error('The image runner returned an invalid output file.');const full=join(this.output,file),meta=await stat(full);if(!meta.isFile()||meta.size<100)throw new Error('The image runner did not create an output image.');const item={id,file,prompt,ratio,transparent,steps,width:Number(result.width)||size[0],height:Number(result.height)||size[1],seed:result.seed??null,createdAt:Date.now()};this.data.items.unshift(item);this.data.items=this.data.items.slice(0,100);await this.save();return this.public(item);}finally{this.active=null;await this.runner('/unload',{}).catch(()=>{});for(const model of loaded)await this.setRouter('load',model).catch(e=>this.log.warn('Could not restore '+model+': '+e.message));}};const job=this.serial.then(task);this.serial=job.catch(()=>{});return job;}
  async remove(id){const item=this.data.items.find(row=>row.id===id);if(!item)throw new Error('Image not found.');await unlink(join(this.output,item.file)).catch(e=>{if(e.code!=='ENOENT')throw e;});this.data.items=this.data.items.filter(row=>row!==item);await this.save();return this.history();}
}
