// OOPIFs have independent CDP node namespaces. Compose their inert models into
// the parent without creating browser tabs or crossing task ownership boundaries.
export class MirrorFrames {
  constructor(root,Session){this.root=root;this.Session=Session;this.children=new Map();this.aliases=new Map();this.ids=new Map();this.next=1_000_000_000;this.offs=[];}
  async start(session){
    const r=this.root;
    const pending=[];this.offs.push(r.cdp.onEvent(session,'Target.attachedToTarget',p=>{if(p.targetInfo.type==='iframe'&&r.live){const job=this.attach(p).catch(()=>{});pending.push(job);}}));
    this.offs.push(r.cdp.onEvent(session,'Target.detachedFromTarget',p=>{for(const [id,c]of this.children)if(c.session===p.sessionId){c.stop();this.children.delete(id);r.schedule();}}));
    await r.cdp.send('Target.setAutoAttach',{autoAttach:true,waitForDebuggerOnStart:false,flatten:true,filter:[{type:'iframe',exclude:false},{exclude:true}]},session);
    await Promise.all(pending);
  }
  async attach(p){
    const r=this.root,id=p.targetInfo.targetId;if(this.children.has(id))return;if(this.children.size>=32){r.off('too-big');return;}
    const cdp={tabs:new Map([[id,p.sessionId]]),get alive(){return r.cdp.alive;},userAgent:r.cdp.userAgent,send:r.cdp.send.bind(r.cdp),onEvent:r.cdp.onEvent.bind(r.cdp)};
    const c=new this.Session({...r.controller,cdp});c.parent=r;c.frameBridge=this;c.resources=r.resources;this.children.set(id,c);
    const socket={readyState:1,get bufferedAmount(){return Math.max(0,...[...r.clients.keys()].map(ws=>ws.bufferedAmount));},send:data=>{const m=JSON.parse(data);if(m.type==='mirror-ack')r.broadcast({...m,epoch:r.epoch,id:this.id(c,m.id)});else if(m.type==='mirror-rich')r.broadcast({...m,epoch:r.epoch,id:this.id(c,m.id),node:this.tree(c,m.node),selection:m.selection?{...m.selection,anchorId:this.id(c,m.selection.anchorId),focusId:this.id(c,m.selection.focusId)}:null});else if(m.type==='mirror-islands')r.broadcast({...m,epoch:r.epoch,rects:m.rects.map(v=>({...v,id:this.id(c,v.id)}))},false);else if(['mirror-state','mirror-layout'].includes(m.type))r.broadcast({...m,epoch:r.epoch,frame:c.session,selection:undefined,rows:m.rows.map(v=>({...v,id:this.id(c,v.id),...(v.anchorId?{anchorId:this.id(c,v.anchorId),focusId:this.id(c,v.focusId)}:{})}))});else if(m.type==='mirror-ops'&&m.ops?.every(op=>op.op==='computed'))r.broadcast({...m,epoch:r.epoch,ops:m.ops.map(op=>({...op,id:this.id(c,op.id)}))});else {if(m.type==='mirror-off')c.failed=true;this.sync(c);r.schedule();}}};
    await c.add(socket);await c.start(id);if(!r.live){c.stop();return;}this.sync(c);r.schedule();
    // Nested cross-site descendants are attached to their immediate target.
    this.offs.push(r.cdp.onEvent(p.sessionId,'Target.attachedToTarget',q=>{if(q.targetInfo.type==='iframe'&&r.live)void this.attach(q).catch(()=>{});}));
    this.offs.push(r.cdp.onEvent(p.sessionId,'Target.detachedFromTarget',q=>{for(const [key,v]of this.children)if(v.session===q.sessionId){v.stop();this.children.delete(key);r.schedule();}}));
    await r.cdp.send('Target.setAutoAttach',{autoAttach:true,waitForDebuggerOnStart:false,flatten:true,filter:[{type:'iframe',exclude:false},{exclude:true}]},p.sessionId).catch(()=>{});
  }
  sync(c){for(const [id,url]of c.frames){this.root.frames.set(id,url);this.root.frameOrigins?.set(id,c.frameOrigins?.get(id));this.root.frameBases?.set(id,c.frameBases?.get(id));(this.root.frameSessions||=new Map()).set(id,c.session);}for(const [url,type]of c.resourceTypes)this.root.resourceTypes.set(url,type);}
  id(c,id){if(!id)return 0;if(this.aliases.has(id))return id;const key=c.session+':'+c.epoch+':'+id;let alias=this.ids.get(key);if(!alias){alias=this.next++;this.ids.set(key,alias);}this.aliases.set(alias,{c,id,epoch:c.epoch});return alias;}
  safe(text){return String(text||'').split(/(\/work\/mirror-res\?[^"')\s]+)/g).map(part=>{if(!part.startsWith('/work/mirror-res?'))return this.root.redact(part);try{const u=new URL(part,'http://mirror'),url=u.searchParams.get('u'),frame=u.searchParams.get('f'),sig=u.searchParams.get('s');if(this.root.resources.valid(url,frame,sig))return this.root.resources.sign(this.root.redact(url),frame);}catch{}return '';}).join('');}
  tree(c,n=c.tree){if(!n)return null;const out={...n,i:this.id(c,n.i)};if(typeof n.v==='string')out.v=this.root.redact(n.v);if(n.a)out.a=n.a.map(([key,value])=>[key,this.safe(value)]);if(n.c)out.c=n.c.map(v=>this.tree(c,v));if(n.s)out.s=n.s.map(v=>this.tree(c,v));if(n.d)out.d=this.tree(c,n.d);return out;}
  child(frame){const c=this.children.get(frame)||[...this.children.values()].find(c=>c.mainFrame===frame);return c?.ready&&!c.failed?c:null;}
  sheets(){return [...this.children.values()].filter(c=>c.ready&&!c.failed).flatMap(c=>(c.ownSheets||[]).map(s=>({...s,text:this.safe(s.text),id:c.session+':'+s.id,owner:this.id(c,s.owner),parent:this.id(c,s.parent),before:this.id(c,s.before)})));}
  async geometry(c,scroll=false,seen=new Set()){if(seen.has(c))throw Error('Frame cycle');seen.add(c);const sources=[this.root,...this.children.values()];let owner,node;for(const s of sources)if(s!==c){const row=[...s.nodes.values()].find(r=>r.node.localName==='iframe'&&[c.mainFrame,c.tab].includes(r.node.frameId));if(row){owner=s;node=row.node;break;}}if(!node)throw Error('Frame host unavailable');if(scroll){await owner.call('DOM.scrollIntoViewIfNeeded',{backendNodeId:node.backendNodeId});await owner.local(node,'function(){return new Promise(r=>this.ownerDocument.defaultView.requestAnimationFrame(()=>this.ownerDocument.defaultView.requestAnimationFrame(()=>r(true))))}');}const {model}=await owner.call('DOM.getBoxModel',{backendNodeId:node.backendNodeId}),q=model.content;if(owner.parent){const g=await this.geometry(owner,scroll,seen);for(let i=0;i<8;i+=2){const p=g.point(q[i],q[i+1]);q[i]=p.x;q[i+1]=p.y;}}const w=c.viewport?.w||model.width,h=c.viewport?.h||model.height;return {q,point:(x,y)=>({x:q[0]+(q[2]-q[0])*x/w+(q[6]-q[0])*y/h,y:q[1]+(q[3]-q[1])*x/w+(q[7]-q[1])*y/h}),axis:Math.abs(q[3]-q[1])<.1&&Math.abs(q[6]-q[0])<.1&&q[2]>q[0]&&q[5]>q[1],sx:(q[2]-q[0])/w,sy:(q[5]-q[1])/h};}
  async input(m,client){if(['mlayout','mvisible'].includes(m.type)){const groups=new Map();if(m.type==='mvisible')for(const c of this.children.values())if(c.live)groups.set(c,[]);for(const id of m.ids||[]){const a=this.aliases.get(id);if(a?.c.live&&a.epoch===a.c.epoch){const ids=groups.get(a.c)||[];ids.push(a.id);groups.set(a.c,ids);}}for(const [c,ids]of groups)await c.enqueue(()=>c.input({...m,epoch:c.epoch,ids},client));return false;}const a=this.aliases.get(m.id||m.anchor);if(!a)return false;if(!a.c.live||a.epoch!==a.c.epoch)return true;const selection=s=>{const out={...s};for(const key of ['anchorId','focusId'])if(key in out){const ref=this.aliases.get(out[key]);out[key]=ref?.c===a.c&&ref.epoch===a.c.epoch?ref.id:0;}return out;};await a.c.enqueue(()=>a.c.input({...selection(m),epoch:a.c.epoch,id:m.id? a.id:0,anchor:m.anchor? a.id:0,...(m.selection?{selection:selection(m.selection)}:{})},client));return true;}
  stop(){for(const off of this.offs)off();this.offs=[];for(const c of this.children.values())c.stop();this.children.clear();this.aliases.clear();this.ids.clear();}
}
