export const REPAIR_PROPERTIES=['font-family','font-size','font-weight','font-style','font-stretch','font-variation-settings','font-feature-settings','line-height','letter-spacing','word-spacing','white-space','text-transform','box-sizing','padding-top','padding-right','padding-bottom','padding-left','margin-top','margin-right','margin-bottom','margin-left'];
export async function richSelection(m,n){if(!n||m.secretIds.has(n.backendNodeId))return null;const offsets=await m.local(n,'function(){const s=this.ownerDocument.getSelection();return this.contains(s.anchorNode)&&this.contains(s.focusNode)?{anchorOffset:s.anchorOffset,focusOffset:s.focusOffset}:null}');if(!offsets)return null;return {...offsets,anchorId:await m.refNode(n,'function(){return this.ownerDocument.getSelection().anchorNode}').catch(()=>0),focusId:await m.refNode(n,'function(){return this.ownerDocument.getSelection().focusNode}').catch(()=>0)};}
export async function measureLayout(m){
  const snap=await m.call('DOMSnapshot.captureSnapshot',{computedStyles:REPAIR_PROPERTIES,includeDOMRects:true}),strings=snap.strings,raw=new Map([...m.nodes.values()].map(r=>[r.node.backendNodeId,r.node])),rows=[];
  for(const d of snap.documents){const l=d.layout;for(let i=0;i<l.nodeIndex.length&&rows.length<80;i++){const node=raw.get(d.nodes.backendNodeId[l.nodeIndex[i]]),r=l.bounds[i];if(!node||node.nodeType!==1||m.secretIds.has(node.backendNodeId)||!r||r[2]<2||r[3]<2)continue;const x=r[0]-d.scrollOffsetX,y=r[1]-d.scrollOffsetY;if(x+r[2]<0||y+r[3]<0||x>m.viewport.w||y>m.viewport.h)continue;
    const style=Object.fromEntries((l.styles[i]||[]).map((v,j)=>[REPAIR_PROPERTIES[j],m.redact(strings[v])]));rows.push({id:node.nodeId,x,y,w:r[2],h:r[3],style});}}
  m.measurements=new Map(rows.map(r=>[r.id,r]));m.broadcast({type:'mirror-layout',epoch:m.epoch,rows});
}
export async function repairLayout(m,msg){const rows=(msg.ids||[]).slice(0,40).map(id=>m.measurements?.get(id)).filter(Boolean);if(rows.length)m.broadcast({type:'mirror-ops',epoch:m.epoch,ops:rows.map(r=>({op:'computed',id:r.id,style:r.style}))});}
export async function transientState(m){
  const {result}=await m.call('Runtime.evaluate',{contextId:m.contexts.get(m.mainFrame),expression:'[...document.querySelectorAll(":hover,:focus,:focus-within,:focus-visible,:active,:invalid")].slice(0,60)',returnByValue:false});if(!result.objectId)return;
  const rows=[];try{const {result:properties}=await m.call('Runtime.getProperties',{objectId:result.objectId,ownProperties:true});for(const p of properties){if(!/^\d+$/.test(p.name)||!p.value?.objectId)continue;const {nodeId:id}=await m.call('DOM.requestNode',{objectId:p.value.objectId}).catch(()=>({nodeId:0})),n=m.nodes.get(id)?.node;if(!n)continue;const state=await m.local(n,'function(){const s=this.ownerDocument.getSelection();return {hover:this.matches(":hover"),focus:this.matches(":focus"),within:this.matches(":focus-within"),visible:this.matches(":focus-visible"),active:this.matches(":active"),invalid:this.matches(":invalid"),start:this.selectionStart,end:this.selectionEnd,direction:this.selectionDirection,...(this.isContentEditable&&this.matches(":focus")&&this.contains(s.anchorNode)&&this.contains(s.focusNode)?{anchorOffset:s.anchorOffset,focusOffset:s.focusOffset}:{})}}').catch(()=>null);if(state){if(state.anchorOffset!==undefined&&!m.secretIds.has(n.backendNodeId)){state.anchorId=await m.refNode(n,'function(){return this.ownerDocument.getSelection().anchorNode}');state.focusId=await m.refNode(n,'function(){return this.ownerDocument.getSelection().focusNode}');}rows.push({id,...state});}}}finally{await m.call('Runtime.releaseObject',{objectId:result.objectId}).catch(()=>{});}
  // Page text selection (drag, double/triple click, Ctrl+A) is drawn by the host; Native shows it so copying works locally. Field selections travel with their rows.
  let selection=null;const offsets=m.root&&await m.local(m.root,'function(){const s=this.getSelection(),edit=x=>{const e=x&&(x.nodeType===1?x:x.parentElement);return !!e?.closest?.("input,textarea,[contenteditable]:not([contenteditable=false])")};return !s||s.isCollapsed||!s.rangeCount||edit(s.anchorNode)||edit(s.focusNode)?null:{anchorOffset:s.anchorOffset,focusOffset:s.focusOffset}}').catch(()=>null);
  if(offsets){const anchorId=await m.refNode(m.root,'function(){return this.getSelection().anchorNode}').catch(()=>0),focusId=await m.refNode(m.root,'function(){return this.getSelection().focusNode}').catch(()=>0);if(anchorId&&focusId)selection={anchorId,focusId,...offsets};}
  const sig=JSON.stringify([rows,selection]);if(sig!==m.stateSig){m.stateSig=sig;m.broadcast({type:'mirror-state',epoch:m.epoch,rows,selection});}
}
