import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {WorkAssets} from '../lib/work-assets.js';
const assets=await new WorkAssets().init();
async function fixture(fn){const server=createServer((req,res)=>{if(!assets.serve(req,res,new URL(req.url,'http://local'))){res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await fn('http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}}
test('HTML versions all eager module URLs and defers finance/images',async()=>{await fixture(async origin=>{const r=await fetch(origin+'/work'),html=await r.text();assert.match(html,new RegExp('/work/app.js\\?v='+assets.release));assert.ok(!html.includes('src="/work/finance.js'));assert.ok(!html.includes('src="/work/images.js'));assert.equal(r.headers.get('cache-control'),'no-cache');});});
test('hashed assets are compressed, privately cacheable, and conditionally reusable',async()=>{await fixture(async origin=>{const url=origin+'/work/app.js?v='+assets.release,r=await fetch(url,{headers:{'Accept-Encoding':'br'}});assert.equal(r.status,200);assert.equal(r.headers.get('content-encoding'),'br');assert.match(r.headers.get('cache-control'),/immutable/);assert.ok((await r.text()).includes('/work/runtime.js?v='+assets.release));const unchanged=await fetch(url,{headers:{'If-None-Match':r.headers.get('etag'),'Accept-Encoding':'br'}});assert.equal(unchanged.status,304);});});
test('old version URLs are never served new bytes and unversioned URLs revalidate',async()=>{await fixture(async origin=>{assert.equal((await fetch(origin+'/work/app.js?v=previous')).status,410);assert.match((await fetch(origin+'/work/app.js')).headers.get('cache-control'),/must-revalidate/);});});
test('smaller alpha texture is used in masks and its WebP body remains bounded',async()=>{const file=assets.files.get('work-buddy-plush.webp');assert.ok(file.body.length<256000);assert.equal(file.body.toString('ascii',0,4),'RIFF');assert.equal(file.body.toString('ascii',8,12),'WEBP');assert.ok(assets.files.get('work-buddy.js').body.toString().includes('/work/plush.webp?v='+assets.release));});
