import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorkEngine} from '../lib/work-server.js';import {CompanionService} from '../lib/work-companion.js';import {FakeHarness} from './fake-harness.mjs';import {hiddenTools} from '../lib/work-tool-scope.js';
const req='a'.repeat(32);
async function setup(){const harness=new FakeHarness(),engine=new WorkEngine(harness,await mkdtemp(join(tmpdir(),'seek-companion-')),console,id=>harness.sessions.get(id)?.goal);await engine.init();let granted=null;const hub={machines:async()=>[],log:console,on:fn=>{hub.listener=fn;return ()=>{};},machineFor:id=>granted?.taskId===id?{id:granted.deviceId}:null};const service=new CompanionService({engine,hub,controlTask:b=>engine.operation(()=>engine.control(b.id,b.action,b.answer,b.requestId,[],{fastAck:true}))});return {service,engine,hub,grant:(deviceId,taskId)=>{granted={deviceId,taskId};}};}
test('desktop task is durably paused until its originating computer grants control',async()=>{
 const s=await setup(),t=await s.service.handle('one',{}, {method:'create',body:{mode:'desktop',text:'Use Notes',requestId:req}});assert.equal(t.status,'paused');await s.engine.tick();assert.equal(s.engine.task(t.id).sessionId,undefined);
 await assert.rejects(s.service.handle('one',{}, {method:'start',body:{id:t.id}}),/Continue/);s.grant('two',t.id);await assert.rejects(s.service.handle('one',{}, {method:'start',body:{id:t.id}}),/Continue/);s.grant('one',t.id);await s.service.handle('one',{}, {method:'start',body:{id:t.id}});assert.equal(s.engine.task(t.id).status,'queued');await s.engine.tick();assert.equal(s.engine.task(t.id).status,'running');
 s.grant(null,null);s.hub.listener({type:'state',id:'one',previousTask:t.id,state:{state:'human'}});await s.engine.operations;assert.equal(s.engine.task(t.id).status,'paused');
});
test('device conversation ownership and rich approvals cannot be bypassed',async()=>{
 const s=await setup(),t=await s.service.handle('one',{}, {method:'create',body:{mode:'browser',text:'Synthetic browser task',requestId:req}});await assert.rejects(s.service.handle('two',{}, {method:'get',body:{id:t.id}}),/not available/);assert.equal((await s.service.handle('two',{}, {method:'list',body:{}})).tasks.length,0);
 s.engine.task(t.id).approval={id:'fixture'};await assert.rejects(s.service.handle('one',{}, {method:'reply',body:{id:t.id,text:'Approve once',requestId:req}}),/Open this task/);assert.equal(s.engine.task(t.id).status,'queued');
});
test('explicit modes bind the tools regardless of task wording and creation is idempotent',async()=>{
 const s=await setup(),body={mode:'desktop',text:'Find a recipe',requestId:req};const a=await s.service.handle('one',{}, {method:'create',body}),b=await s.service.handle('one',{}, {method:'create',body});assert.equal(a.id,b.id);assert.equal(s.engine.store.tasks.length,1);
 const tools=['desktop_observe','viewer_navigate'];assert.deepEqual(hiddenTools({objective:'Find a recipe',companion:{mode:'desktop'}},tools),['viewer_navigate']);assert.deepEqual(hiddenTools({objective:'Use my computer',companion:{mode:'browser'}},tools),['desktop_observe']);assert.deepEqual(hiddenTools({objective:'Use my computer',companion:{mode:'chat'}},tools),['desktop_observe']);
});
test('long histories stay within encrypted transport bounds',async()=>{const s=await setup(),t=await s.engine.create({objective:'Synthetic'});t.messages=Array.from({length:100},()=>({role:'assistant',text:'🐙'.repeat(8000)}));assert.ok(Buffer.byteLength(JSON.stringify(s.service.snapshot(t)))<60000);assert.equal(s.service.snapshot(t,false).messages.length,0);});
test('remote tasks use standing device permission and bind execution to the selected computer',async()=>{
 const s=await setup();s.hub.machines=async()=>[{id:'mac',name:'Studio Mac',verified:true,remoteGrant:true,online:true,state:'human'}];const t=await s.service.handle('phone',{}, {method:'create',body:{mode:'desktop',text:'Use Notes',computerId:'mac',requestId:req}});assert.equal(t.status,'queued');assert.equal(t.remote,true);assert.equal(s.engine.task(t.id).execution.deviceId,'mac');assert.equal(s.engine.task(t.id).execution.granted,false);assert.equal(s.engine.task(t.id).companion.deviceId,'phone');
 s.hub.machines=async()=>[{id:'mac',verified:true,remoteGrant:false,online:true}];await assert.rejects(s.service.createRemote({objective:'Synthetic'},'mac'),/not enabled/);s.hub.machines=async()=>[{id:'mac',verified:true,remoteGrant:true,online:false}];await assert.rejects(s.service.createRemote({objective:'Synthetic'},'mac'),/offline/);
});
test('remote computer selection survives schedules, attachments and recurring occurrences',async()=>{
 const s=await setup();s.hub.machines=async()=>[{id:'mac',name:'Studio Mac',verified:true,remoteGrant:true,online:false,state:'offline'}];const t=await s.service.createRemote({objective:'Read the supplied brief in Notes',runAt:new Date(Date.now()+3600000).toISOString(),repeatHours:24,files:[{name:'brief.txt',data:Buffer.from('Synthetic brief').toString('base64')}]},'mac');assert.equal(t.status,'scheduled');assert.equal(t.inputs.length,1);t.status='complete';t.completedAt=Date.now();t.execution.granted=true;await s.engine.scheduleNext(t);const next=s.engine.store.tasks.find(x=>x.id!==t.id);assert.equal(next.execution.deviceId,'mac');assert.equal(next.execution.granted,false);assert.equal(next.status,'scheduled');assert.equal(next.inputs.length,1);
});
