// Headless Studio journeys using synthetic image metadata and loopback fixtures.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CdpBrowser} from '../lib/cdp.js';
import {WorkAssets} from '../lib/work-assets.js';
import {WorkUpdates} from '../lib/work-updates.js';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1cAAAAASUVORK5CYII=','base64');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
test('Studio preserves drafts/settings, queues once, defers/cancels, inspects/compares, and restores deleted images',async()=>{
  const assets=await new WorkAssets().init(),streams=new Set(),state={language:{name:'Qwen 3.8 · 27B',state:'ready'},image:{name:'Qwen Image 2.1',state:'standby'},active:false,job:null};
  const data={items:[{id:'first',file:'first.png',url:'/qwen-image/api/file?id=first',prompt:'A warm watercolor harbor.',ratio:'portrait',steps:40,transparent:true,livePreview:false,seed:93,width:896,height:1152,createdAt:Date.now()},{id:'second',file:'second.png',url:'/qwen-image/api/file?id=second',prompt:'A cool watercolor harbor.',ratio:'wide',steps:24,transparent:false,livePreview:true,seed:7,width:1280,height:720,createdAt:Date.now()-1000}],deleted:[],queue:[]};
  const starts=[],mutations=[];let failNext=false;
  const updates=new WorkUpdates({store:{version:1,settings:{name:'Seek'},tasks:[]}},{health:()=>({model:'ready',models:state})});
  const server=createServer(async(req,res)=>{
    const url=new URL(req.url,'http://fixture'),json=(value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};
    if(url.pathname==='/work/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('event: revision\ndata: 1\n\n');streams.add(res);res.on('close',()=>streams.delete(res));return;}
    if(url.pathname==='/work/api/updates')return json(updates.changed(url.searchParams.get('since')));
    if(url.pathname==='/qwen-image/api/status')return json({ready:true,available:true,queue:data.queue,active:state.active?state.job:null});
    if(url.pathname==='/qwen-image/api/history')return json(data);
    if(['/qwen-image/api/file','/qwen-image/api/preview'].includes(url.pathname)){res.writeHead(200,{'Content-Type':'image/png'});res.end(png);return;}
    if(url.pathname.startsWith('/qwen-image/api/')&&req.method==='POST'){
      let body='';for await(const chunk of req)body+=chunk;body=JSON.parse(body);const action=url.pathname.split('/').at(-1);mutations.push([action,body]);
      if(action==='start'){starts.push(body);if(failNext){failNext=false;return json({error:'Fixture uncertain acknowledgment'},503);}const id='queued-'+starts.length;data.queue.push({id,prompt:body.prompt,phase:'queued',deferred:false});return json({id,accepted:true,phase:'queued'},202);}
      if(action==='defer'){const job=data.queue.find(job=>job.id===body.id);job.deferred=body.deferred;job.phase=body.deferred?'deferred':'queued';return json(data);}
      if(action==='cancel'){data.queue=data.queue.filter(job=>job.id!==body.id);return json({job:{id:body.id,phase:'cancelled'}});}
      if(action==='delete'){const image=data.items.find(item=>item.id===body.id);data.items=data.items.filter(item=>item!==image);data.deleted.push({...image,deletedAt:Date.now()});return json(data);}
      if(action==='favorite'){const image=data.items.find(item=>item.id===body.id);if(body.favorite)image.favoriteAt=Date.now();else delete image.favoriteAt;return json(data);}
      if(action==='undelete'){const image=data.deleted.find(item=>item.id===body.id);data.deleted=data.deleted.filter(item=>item!==image);delete image.deletedAt;data.items.push(image);return json(data);}
    }
    if(!assets.serve(req,res,url)){res.writeHead(404);res.end();}
  });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
  const ui=new CdpBrowser({headless:true,userDataDir:await mkdtemp(join(tmpdir(),'seek-studio-fixture-')),windowSize:'1440,1050'});let tab;
  const evaluate=expression=>ui.evaluate(tab,expression),wait=async expression=>{const end=Date.now()+5000;while(Date.now()<end){if(await evaluate(expression))return;await sleep(20);}throw new Error('Studio fixture timeout: '+expression);};
  const save=async name=>{if(process.env.SEEK_STUDIO_TEST_OUTPUT){await mkdir(process.env.SEEK_STUDIO_TEST_OUTPUT,{recursive:true});await writeFile(join(process.env.SEEK_STUDIO_TEST_OUTPUT,name+'.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));}};
  const open=async()=>{await wait("!!document.querySelector('[data-view=images]')");await evaluate("document.querySelector('[data-view=images]').click();true");await wait("document.querySelectorAll('.image-card').length===2");};
  try{
    await ui.launch();tab=await ui.newTab(origin+'/work');await open();await save('studio-desktop');
    await evaluate("document.querySelector('[data-image-reuse=first]').click();true");assert.deepEqual(await evaluate("(()=>{const f=document.querySelector('#image-create');return [f.elements.prompt.value,f.elements.ratio.value,f.elements.steps.value,f.elements.transparent.checked,f.elements.livePreview.checked,f.elements.seed.value]})()"),['A warm watercolor harbor.','portrait','40',true,false,'93']);
    await ui.navigate(tab,origin+'/work');await open();assert.equal(await evaluate("document.querySelector('#image-create [name=prompt]').value"),'A warm watercolor harbor.','Prompt survives a complete page reload');assert.equal(await evaluate("document.querySelector('#image-create [name=livePreview]').checked"),false);
    await evaluate("const f=document.querySelector('#image-create');f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));true");await wait("document.querySelector('.studio-queue')?.textContent.includes('Waiting for the GPU')");assert.equal(starts.length,1);assert.equal(starts[0].seed,'93');assert.ok(starts[0].requestId);
    await evaluate("document.querySelector('[data-image-defer]').click();true");await wait("document.querySelector('.studio-queue')?.textContent.includes('Deferred until you resume')");await evaluate("document.querySelector('[data-image-defer]').click();true");await wait("document.querySelector('.studio-queue')?.textContent.includes('Waiting for the GPU')");await evaluate("document.querySelector('[data-image-cancel]').click();true");await wait("!document.querySelector('.studio-queue')");
    const now=Date.now();state.active=true;state.language.state='standby';state.image.state='creating';state.job={id:'a9b13c91-50f8-4e6b-81c4-94512e7b0c68',phase:'creating',phaseAt:now,startedAt:now,phases:[],sampling:{step:12,total:30,updatedAt:now},preview:{step:12,total:30,updatedAt:now,width:1,height:1},livePreview:true};for(const stream of streams)stream.write('event: revision\ndata: 1\n\n');await wait("document.querySelector('.image-live-preview img')?.naturalWidth>0");await save('studio-creating-desktop');assert.equal(await evaluate("document.querySelector('.image-preview-frame').getBoundingClientRect().height>document.querySelector('.model-journey').getBoundingClientRect().height"),true,'Actual preview dominates compact model activity');
    await evaluate("window.samePhaseRibbon=document.querySelector('#model-status .model-indicator');true");state.job.preview.updatedAt++;state.job.sampling.updatedAt++;for(const stream of streams)stream.write('event: revision\ndata: 1\n\n');await sleep(100);assert.equal(await evaluate("document.querySelector('#model-status .model-indicator')===samePhaseRibbon"),true,'An unchanged phase and sampling count do not remount the live announcement');
    state.active=false;state.language.state='ready';state.image.state='standby';state.job.phase='complete';state.job.finishedAt=Date.now();for(const stream of streams)stream.write('event: revision\ndata: 1\n\n');await wait("!document.querySelector('.image-live-preview img')");
    await evaluate("document.querySelector('[data-image-inspect=first]').click();true");await wait("document.querySelector('#studio-inspector')?.open");assert.equal(await evaluate("document.activeElement.closest('dialog')?.id"),'studio-inspector');assert.ok(await evaluate("document.querySelector('#studio-inspector').textContent.includes('93')"));await ui.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27,nativeVirtualKeyCode:27},ui.tabs.get(tab));await ui.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27,nativeVirtualKeyCode:27},ui.tabs.get(tab));await wait("!document.querySelector('#studio-inspector')");
    await evaluate("document.querySelector('[data-image-compare=first]').click();document.querySelector('[data-image-compare=second]').click();document.querySelector('[data-image-compare-open]').click();true");await wait("document.querySelector('#studio-inspector')?.open");assert.equal(await evaluate("document.querySelectorAll('.studio-inspector-grid figure').length"),2);await save('studio-compare');await evaluate("document.querySelector('[data-image-close]').click();true");
    assert.equal(await evaluate("document.querySelector('[data-image-favorites]').disabled"),true,'Favorites filter waits for a favorite');await evaluate("document.querySelector('.image-favorite[data-image-favorite=second]').click();true");await wait("document.querySelector('.image-favorite[data-image-favorite=second]')?.getAttribute('aria-pressed')==='true'");await evaluate("document.querySelector('[data-image-favorites]').click();true");await wait("document.querySelectorAll('.image-card').length===1");assert.equal(await evaluate("document.querySelector('.image-card [data-image-inspect]').dataset.imageInspect"),'second');await evaluate("document.querySelector('.image-favorite[data-image-favorite=second]').click();true");await wait("document.querySelectorAll('.image-card').length===2");assert.equal(await evaluate("document.querySelector('[data-image-favorites]').getAttribute('aria-pressed')"),'false','Removing the last favorite returns to all images');
    await evaluate("document.querySelector('[data-image-delete=first]').click();true");await wait("document.querySelectorAll('.image-card').length===1");assert.equal(data.deleted.length,1);await evaluate("document.querySelector('[data-image-undo=first]').click();true");await wait("document.querySelectorAll('.image-card').length===2");assert.equal(data.deleted.length,0);
    failNext=true;await evaluate("document.querySelector('#image-create').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));true");await wait("!document.querySelector('#image-create .primary').disabled");await ui.navigate(tab,origin+'/work');await open();await evaluate("document.querySelector('#image-create').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));true");await wait("document.querySelector('.studio-queue')!==null");assert.equal(starts[1].requestId,starts[2].requestId,'Uncertain requests retain their ID through reload');
    await ui.send('Emulation.setDeviceMetricsOverride',{width:320,height:740,deviceScaleFactor:1,mobile:true},ui.tabs.get(tab));assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);await save('studio-mobile');
  }finally{for(const stream of streams)stream.end();await ui.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
});
