import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {EventEmitter} from 'node:events';
import {WebSocketServer} from 'ws';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {BrowserController} from '../lib/index.js';
import {CdpBrowser} from '../lib/cdp.js';
import {WorkAssets} from '../lib/work-assets.js';
import {FRAME_HTML,FRAME_CSP} from '../lib/mirror-shape.js';
import {MirrorSession} from '../lib/mirror.js';
const mirrorCall=MirrorSession.prototype.call;MirrorSession.prototype.call=function(method,params){this.fixturePending||=new Set();this.fixturePending.add(method);return mirrorCall.call(this,method,params).finally(()=>this.fixturePending.delete(method));};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const until=async(fn,label)=>{for(let i=0;i<120;i++){if(await fn()){if(process.env.SEEK_MIRROR_TEST_ARTIFACTS)console.log('Verified: '+label);return;}await wait(50);}throw new Error('Timed out: '+label);};
const assets=await new WorkAssets().init();let c;
const iconFont=await readFile(new URL('./fixtures/fixture-icons.woff2',import.meta.url));
const server=createServer(async(req,res)=>{
  const url=new URL(req.url,'http://fixture');
  if(assets.serve(req,res,url))return;
  if(url.pathname==='/work/mirror-frame'){res.writeHead(200,{'Content-Type':'text/html','Content-Security-Policy':FRAME_CSP});res.end(FRAME_HTML);return;}
  if(url.pathname==='/work/mirror-res'){try{const r=await c.mirror.resources.get(url.searchParams.get('u'),url.searchParams.get('f'),url.searchParams.get('s'));res.writeHead(200,{'Content-Type':r.type});res.end(r.data);}catch{res.writeHead(404);res.end();}return;}
  if(url.pathname==='/icons.woff2'){res.writeHead(200,{'Content-Type':'application/font-woff2'});res.end(iconFont);return;}
  if(url.pathname==='/cascade.css'){res.setHeader('Content-Type','text/css');res.end('@layer base,theme; @import url("/inactive.css") layer(theme) screen and (min-width:2000px); @import url("/active.css") layer(base) supports(display:grid) screen; #cssorder{color:rgb(1,2,3)}');return;}
  if(url.pathname==='/inactive.css'){res.setHeader('Content-Type','text/css');res.end('#cssorder{border:40px solid red!important}');return;}
  if(url.pathname==='/active.css'){res.setHeader('Content-Type','text/css');res.end('#cssorder{padding:7px}');return;}
  if(['/image','/assets/dot.png'].includes(url.pathname)){res.writeHead(200,{'Content-Type':'image/png','Set-Cookie':'fixture=ok; SameSite=Lax'});res.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf9sAAAAASUVORK5CYII=','base64'));return;}
  if(url.pathname==='/protected'){if(!String(req.headers.cookie||'').includes('fixture=ok')){res.writeHead(403);res.end();return;}res.writeHead(200,{'Content-Type':'image/png','Set-Cookie':'must_not_forward=secret'});res.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf9sAAAAASUVORK5CYII=','base64'));return;}
  res.setHeader('Content-Type','text/html');
  if(url.pathname==='/ui'){res.end(`<style>#stage{position:relative;width:700px;height:600px}</style><div id="stage"></div><script type="module">import {MirrorView} from '/work/mirror.js';window.out=[];window.fail=[];window.view=new MirrorView(document.querySelector('#stage'),{send:m=>out.push(m),onFallback:r=>fail.push(r)});view.show(true);window.feed=m=>view.message(m);await view.ready;window.ready=true;</script>`);return;}
  if(url.pathname==='/sheet'){res.end('<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/work/style.css"><div id="toast" hidden></div><script type="module" src="/work/browser.js"></script>');return;}
  if(url.pathname==='/captcha'){res.end('<h1>Verify you are human</h1>');return;}
  if(url.pathname==='/inner'){res.end('<h2>Nested frame content</h2><button id="nestedTap" onclick="window.hit=event.isTrusted;this.dataset.hit=String(event.isTrusted)">Nested tap</button><input id="nestedInput"><div id="nestedRich" contenteditable="true">Frame rich</div><canvas id="nestedIsland" width="60" height="60" style="position:fixed;left:20px;top:90px"></canvas><input id="frameSecret" autocomplete="cc-number" value="FIXTURE_FRAME_SECRET" style="position:fixed;left:20px;top:110px;width:60px;height:20px"><script>const ctx=document.querySelector("canvas").getContext("2d");ctx.fillStyle="red";ctx.fillRect(0,0,60,60);</script>');return;}
  res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mirror fixture</title><link rel="stylesheet" href="/cascade.css"><style>@font-face{font-family:SeekFixtureIcons;src:url('/icons.woff2') format('woff2')}.fixture-icon{font:32px SeekFixtureIcons;position:fixed;top:1px;right:1px}.fixture-icon::before{content:'\\f1ba'}body{font:18px sans-serif}button,input{font-size:18px}#island{width:80px;height:80px}#cssorder{color:rgb(4,5,6);max-width:300px}#drag{position:fixed;bottom:8px;left:8px;width:100px;height:40px;background:red;touch-action:none}#tap:hover{outline:3px solid blue}</style><style media="(min-width:2000px)">#cssorder{color:purple!important}</style>
  <i class="fixture-icon" id="fixture-icon" aria-label="Menu"></i>
  <p id="cssorder">A wrapping paragraph to compare geometry, fonts and line breaks between host Chrome and Native Chrome.</p><div id="drag" tabindex="0">Drag</div><select id="choice"><option value="one">One</option><option value="two">Two</option></select><input id="slider" type="range" min="0" max="100" step="10" value="0" oninput="window.rangeTrusted=event.isTrusted"><div id="rich" contenteditable="true">Rich text</div><div id="card-rich" contenteditable="true" autocomplete="cc-number">PRIVATE_RICH_CARD</div><button id="double" ondblclick="window.doubleTrusted=event.isTrusted">Double click</button><button id="popup" onclick="window.open('/inner','fixture-popup')">Popup</button>
  <h1>Mirror fixture</h1><div id="password-wrapper"><label for="password">Password</label></div><svg><defs><filter id="blur"><feGaussianBlur stdDeviation="2"/></filter></defs></svg><input id="message" value="hello"><input id="email" type="email"><input id="password" type="password" value="FIXTURE_PASSWORD"><input id="card" autocomplete="cc-number" value="4242424242424242"><span id="reflected">FIXTURE_PASSWORD</span>
  <button id="tap" onclick="window.hit=event.isTrusted;const d=document.createElement('div');d.innerHTML='<span id=inserted>Inserted subtree</span>';document.body.append(d)">Tap</button><p id="result"></p><div id="shadow"></div><img src="/image"><iframe src="/inner"></iframe><iframe id="cross" src="http://localhost:${server.address().port}/inner"></iframe><canvas id="island" width="80" height="80"></canvas><textarea id="multiline">Line</textarea><iframe id="srcdoc" srcdoc="&lt;base href='/assets/'&gt;&lt;img id='srcdoc-image' src='dot.png'&gt;"></iframe><video id="video-island" style="width:120px;height:60px"></video>
  <script>window.dragEvents=[];const drag=document.querySelector('#drag');drag.onpointerdown=e=>{dragEvents.push(['down',e.isTrusted]);drag.setPointerCapture(e.pointerId)};drag.onpointermove=e=>{if(e.buttons)dragEvents.push(['move',e.isTrusted])};drag.onpointerup=e=>{dragEvents.push(['up',e.isTrusted]);drag.style.background='green'};document.querySelector('#choice').onchange=e=>window.selectTrusted=e.isTrusted;window.richEvents=[];document.querySelector('#rich').addEventListener('compositionupdate',e=>richEvents.push(['composition',e.isTrusted]));const root=document.getElementById('shadow').attachShadow({mode:'closed'});window.sheet=new CSSStyleSheet();sheet.replaceSync('b{color:blue}');root.adoptedStyleSheets=[sheet];root.innerHTML='<b>Closed shadow text</b>';document.querySelector('#password').addEventListener('input',e=>document.querySelector('#reflected').textContent=e.target.value);</script>`);
});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const wss=new WebSocketServer({noServer:true,perMessageDeflate:{threshold:2048}});server.on('upgrade',(req,socket,head)=>wss.handleUpgrade(req,socket,head,ws=>c.addClient(ws)));
class Socket extends EventEmitter{readyState=1;bufferedAmount=0;messages=[];send(data){if(typeof data==='string')this.messages.push(JSON.parse(data));}terminate(){this.emit('close');}}
c=new BrowserController({headless:true,windowWidth:900,windowHeight:700,intervalMs:400,quality:40,browserOptions:{userDataDir:await mkdtemp(join(tmpdir(),'seek-mirror-test-'))}});const ws=new Socket();
const viewer=new CdpBrowser({headless:true,userDataDir:await mkdtemp(join(tmpdir(),'seek-mirror-viewer-'))});
const messages=()=>ws.messages.filter(m=>m.type?.startsWith('mirror-'));
function find(tree,id){if((tree.a||[]).some(a=>a[0]==='id'&&a[1]===id))return tree;for(const n of [...tree.c||[],...tree.s||[],...tree.d?[tree.d]:[]]){const hit=find(n,id);if(hit)return hit;}}
let checks=0;const check=fn=>{fn();checks++;};
const comparisons=[];
try{
  await viewer.launch();await c.start(base);await c.cdp.evaluate(c.activeTabId,'Element.prototype.getBoundingClientRect=()=>undefined');c.addClient(ws);await c.takeControl();ws.emit('message',Buffer.from(JSON.stringify({type:'mirror',on:true})));await until(()=>messages().some(m=>m.type==='mirror-reset'),'server snapshot');
  let reset=messages().findLast(m=>m.type==='mirror-reset');check(()=>assert.equal(JSON.stringify(messages()).includes('FIXTURE_PASSWORD'),false));check(()=>assert.equal(JSON.stringify(messages()).includes('4242424242424242'),false));
  check(()=>assert.ok(JSON.stringify(reset.tree).includes('Closed shadow text')));check(()=>assert.ok(JSON.stringify(reset.tree).includes('Nested frame content')));check(()=>assert.equal(find(reset.tree,'island').island,'canvas'));check(()=>assert.ok(reset.sheets.some(s=>s.text.includes('color: blue'))));
  await until(()=>{const d=find(c.mirror.tree,'cross')?.d;return d&&find(d,'nestedInput');},'native cross-site frame');check(()=>assert.equal(find(c.mirror.tree,'cross').island,undefined));
  check(()=>assert.ok(!JSON.stringify(messages()).includes('PRIVATE_RICH_CARD')));
  const input=async(type,id,extra={})=>{await c._onMessage(JSON.stringify({type,epoch:c.mirror.epoch,id,...extra}),ws);};
  const crossInput=find(find(c.mirror.tree,'cross').d,'nestedInput');await input('minput',crossInput.i,{seq:1,at:0,del:0,ins:'cross-site edit',value:'cross-site edit'});const child=c.mirror.frameBridge.children.values().next().value;check(()=>assert.equal(child.values.get(child.nodes.get(c.mirror.frameBridge.aliases.get(crossInput.i).id).node.backendNodeId)?.v,'cross-site edit'));
  await input('mtap',find(find(c.mirror.tree,'cross').d,'nestedTap').i,{rx:.5,ry:.5});const crossTap=child.nodes.get(c.mirror.frameBridge.aliases.get(find(find(c.mirror.tree,'cross').d,'nestedTap').i).id).node;assert.equal(await child.local(crossTap,'function(){return this.dataset.hit}'),'true');checks++;
  const frameRich=find(find(c.mirror.tree,'cross').d,'nestedRich'),frameText=frameRich.c[0];await input('mrich',frameRich.i,{seq:2,inputType:'insertText',text:'Native frame',selection:{anchorId:frameText.i,anchorOffset:0,focusId:frameText.i,focusOffset:10}});await until(()=>messages().some(m=>m.type==='mirror-rich'&&m.id===frameRich.i&&m.node.c[0]?.v==='Native frame'),'cross-frame canonical rich text');checks++;
  const srcdocImage=find(find(c.mirror.tree,'srcdoc').d,'srcdoc-image'),srcdocResource=new URL(srcdocImage.a.find(a=>a[0]==='src')[1],base);assert.equal(srcdocResource.searchParams.get('u'),base+'/assets/dot.png');assert.equal((await fetch(srcdocResource)).status,200);checks++;
  await input('mselect',find(reset.tree,'choice').i,{value:'two'});assert.equal(await c.cdp.evaluate(c.activeTabId,'window.selectTrusted'),true);checks++;
  await input('minput',find(reset.tree,'slider').i,{seq:1,at:0,del:1,ins:'50',value:'50'});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#slider').value"),'50');assert.equal(await c.cdp.evaluate(c.activeTabId,'rangeTrusted'),true);checks++;
  const drag=find(reset.tree,'drag').i;for(const [event,rx,buttons]of [['down',.5,1],['move',2,1],['up',2,0]])await input('mpointer',drag,{event,rx,ry:.5,buttons,button:'left'});assert.deepEqual(await c.cdp.evaluate(c.activeTabId,'dragEvents'),[['down',true],['move',true],['up',true]]);checks++;
  const dbl=find(reset.tree,'double').i;for(const clickCount of [1,2])for(const event of ['down','up'])await input('mpointer',dbl,{event,rx:.5,ry:.5,buttons:event==='down'?1:0,button:'left',clickCount});assert.equal(await c.cdp.evaluate(c.activeTabId,'doubleTrusted'),true);checks++;
  const rich=find(reset.tree,'rich').i;await input('minput',rich,{seq:1,at:0,del:9,ins:'Editable text',value:'Editable text'});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#rich').textContent"),'Editable text');checks++;
  await input('mcomposition',rich,{phase:'start',start:0,end:13,text:''});await input('mcomposition',rich,{phase:'update',text:'日本'});await input('mcomposition',rich,{phase:'end',text:'日本'});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#rich').textContent"),'日本');assert.ok((await c.cdp.evaluate(c.activeTabId,'richEvents')).some(e=>e[0]==='composition'&&e[1]));checks++;
  await input('mtap',find(reset.tree,'nestedTap').i,{rx:.5,ry:.5});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('iframe').contentWindow.hit"),true);checks++;
  await input('minput',find(reset.tree,'nestedInput').i,{seq:1,at:0,del:0,ins:'nested input',value:'nested input'});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('iframe').contentDocument.querySelector('input').value"),'nested input');checks++;
  await input('mtap',find(reset.tree,'tap').i,{rx:.5,ry:.5});await until(()=>JSON.stringify(messages()).includes('Inserted subtree'),'inserted subtree');assert.equal(await c.cdp.evaluate(c.activeTabId,'window.hit'),true);checks++;
  await input('minput',find(reset.tree,'message').i,{seq:1,at:0,del:5,ins:'native',value:'native'});assert.equal(await c.cdp.evaluate(c.activeTabId,'document.querySelector("#message").value'),'native');checks++;
  await input('mselection',find(reset.tree,'message').i,{start:1,end:4,direction:'backward'});assert.deepEqual(await c.cdp.evaluate(c.activeTabId,"(()=>{const n=document.querySelector('#message');return [n.selectionStart,n.selectionEnd,n.selectionDirection]})()"),[1,4,'backward']);checks++;
  for(const event of ['keyDown','keyUp'])await input('mkey',find(reset.tree,'message').i,{event,key:'z',code:'KeyZ',windowsVirtualKeyCode:90,modifiers:2});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#message').value"),'hello');checks++;
  for(const event of ['keyDown','keyUp'])await input('mkey',find(reset.tree,'message').i,{event,key:'y',code:'KeyY',windowsVirtualKeyCode:89,modifiers:2});assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#message').value"),'native');checks++;
  await input('minput',find(reset.tree,'password').i,{seq:2,at:0,del:16,ins:'NEW_PRIVATE_PASSWORD'});await wait(300);assert.equal(await c.cdp.evaluate(c.activeTabId,'document.querySelector("#password").value'),'NEW_PRIVATE_PASSWORD');checks++;
  check(()=>assert.ok(!JSON.stringify(messages()).includes('NEW_PRIVATE_PASSWORD')));
  const imgBefore=(function walk(n){if(n.t==='img')return n;for(const x of n.c||[]){const hit=walk(x);if(hit)return hit;}})(c.mirror.tree).a.find(a=>a[0]==='src')[1];
  await input('minput',find(reset.tree,'password').i,{seq:3,at:0,del:20,ins:'q'});await until(()=>find(c.mirror.tree,'password')?.len===1,'single character secret');
  const reflected=find(c.mirror.tree,'reflected');check(()=>assert.equal(reflected.c[0]?.v||'',''));
  const imgAfter=(function walk(n){if(n.t==='img')return n;for(const x of n.c||[]){const hit=walk(x);if(hit)return hit;}})(c.mirror.tree).a.find(a=>a[0]==='src')[1];check(()=>assert.equal(imgAfter,imgBefore));
  await input('minput',find(reset.tree,'password').i,{seq:4,at:0,del:1,ins:'NEW_PRIVATE_PASSWORD'});
  await c.cdp.evaluate(c.activeTabId,"document.querySelector('#password').type='text';document.styleSheets[1].insertRule('#result{color:rgb(3,4,5)}',0);sheet.insertRule('b{background:rgb(6,7,8)}',0);document.querySelector('#tap').style.padding='20px'");
  await until(()=>JSON.stringify(messages()).includes('rgb(6, 7, 8)'),'CSSOM mutation');check(()=>assert.ok(!JSON.stringify(messages()).includes('NEW_PRIVATE_PASSWORD')));
  const beforeCount=messages().length;ws.bufferedAmount=2*1024*1024;await c.cdp.evaluate(c.activeTabId,"document.querySelector('#result').textContent='Backpressure recovered'");await wait(350);check(()=>assert.equal(messages().length,beforeCount));ws.bufferedAmount=0;await until(()=>messages().findLast(m=>m.type==='mirror-reset')?.tree&&JSON.stringify(messages().findLast(m=>m.type==='mirror-reset').tree).includes('Backpressure recovered'),'drain reset');
  const image=find(c.mirror.tree,'message');assert.ok(image);const img=[...c.mirror.nodes.values()].find(r=>r.node.localName==='img').node;const wireImage=(function walk(n){if(n.i===img.nodeId)return n;for(const x of n.c||[]){const hit=walk(x);if(hit)return hit;}})(c.mirror.tree);
  const resource=new URL(wireImage.a.find(a=>a[0]==='src')[1],base);const fetched=await fetch(resource);assert.equal(fetched.status,200);checks++;resource.searchParams.set('u',base+'/not-signed');assert.equal((await fetch(resource)).status,404);checks++;
  const protectedImage=await fetch(new URL(c.mirror.resources.sign(base+'/protected',c.mirror.mainFrame),base));assert.equal(protectedImage.status,200);assert.equal(protectedImage.headers.get('set-cookie'),null);checks++;
  const privateImage=await fetch(new URL(c.mirror.resources.sign('http://localhost:'+server.address().port+'/protected',c.mirror.mainFrame),base));assert.equal(privateImage.status,404);checks++;
  const ui=await viewer.newTab(base+'/ui'),us=viewer.tabs.get(ui);await until(()=>viewer.evaluate(ui,'window.ready||false'),'client frame canary');
  const sendUI=async m=>{const {result}=await viewer.send('Runtime.evaluate',{expression:'window',returnByValue:false},us);await viewer.send('Runtime.callFunctionOn',{objectId:result.objectId,functionDeclaration:'function(m){return window.feed(m)}',arguments:[{value:m}],awaitPromise:true,returnByValue:true},us);await viewer.send('Runtime.releaseObject',{objectId:result.objectId},us);};
  await sendUI(c.mirror.resetMessage());await wait(100);assert.deepEqual(await viewer.evaluate(ui,'window.fail'),[]);checks++;
  assert.equal(await viewer.evaluate(ui,"view.frame.contentDocument.querySelector('h1').textContent"),'Mirror fixture');checks++;
  assert.equal(await viewer.evaluate(ui,"(async()=>{await view.doc.fonts.load('32px SeekFixtureIcons','\\uf1ba');const ctx=view.doc.createElement('canvas').getContext('2d');ctx.font='32px SeekFixtureIcons';return [...view.doc.fonts].some(f=>f.family==='SeekFixtureIcons'&&f.status==='loaded')&&getComputedStyle(view.doc.querySelector('#fixture-icon'),'::before').content.includes('\\uf1ba')&&Math.abs(ctx.measureText('\\uf1ba').width-32)<.1;})()"),true);checks++;
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#password-wrapper').textContent"),'Password');checks++;
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('feGaussianBlur').namespaceURI"),'http://www.w3.org/2000/svg');checks++;
  assert.equal(await viewer.evaluate(ui,"view.frame.contentDocument.querySelector('#password').value"),'•'.repeat(20));checks++;
  assert.equal(await viewer.evaluate(ui,"view.frame.contentDocument.querySelector('#shadow').shadowRoot.querySelector('b').textContent"),'Closed shadow text');checks++;
  assert.equal(await viewer.evaluate(ui,"view.frame.contentDocument.querySelector('#shadow').shadowRoot.querySelector('b').getAttribute('style')"),null);checks++;
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('iframe').contentDocument.querySelector('h2').textContent"),'Nested frame content');checks++;
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#cross').contentDocument.querySelector('input').value"),'cross-site edit');checks++;
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#card-rich').textContent"),'•'.repeat(17));checks++;
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#srcdoc').contentDocument.querySelector('img').src.includes('mirror-res')"),true);checks++;
  assert.deepEqual(await viewer.evaluate(ui,"(()=>{const n=view.doc.querySelector('#video-island');return [n.localName,n.getBoundingClientRect().width,n.getBoundingClientRect().height]})()"),['div',120,60]);checks++;
  const cssNode=c.mirror.nodes.get(find(c.mirror.tree,'cssorder').i).node;
  const geometryFunction='function(){const r=this.getBoundingClientRect(),s=getComputedStyle(this),range=this.ownerDocument.createRange();range.selectNodeContents(this);return {w:r.width,h:r.height,color:s.color,padding:s.padding,border:s.borderWidth,font:s.font,lineRects:[...range.getClientRects()].map(r=>[r.width,r.height])}}';
  const hostGeometry=await c.mirror.local(cssNode,geometryFunction),nativeGeometry=await viewer.evaluate(ui,'('+geometryFunction+').call(view.doc.querySelector("#cssorder"))');assert.deepEqual(nativeGeometry,hostGeometry);assert.equal(nativeGeometry.color,'rgb(4, 5, 6)');assert.equal(nativeGeometry.padding,'7px');assert.equal(nativeGeometry.border,'0px');checks++;
  await viewer.evaluate(ui,'window.stableStyles=[...view.styleNodes.values()];view.setSheets(view.lastSheets)');assert.equal(await viewer.evaluate(ui,'stableStyles.every((s,i)=>s===[...view.styleNodes.values()][i])'),true);checks++;
  await viewer.send('Emulation.setDeviceMetricsOverride',{width:1100,height:900,deviceScaleFactor:1,mobile:false},us);await viewer.evaluate(ui,"document.querySelector('#stage').style.width='900px'");await wait(100);
  await c.cdp.send('DOM.scrollIntoViewIfNeeded',{nodeId:cssNode.nodeId},c.cdp.tabs.get(c.activeTabId));await wait(100);
  const box=await c.mirror.local(cssNode,'function(){const r=this.getBoundingClientRect();return {x:r.left+this.ownerDocument.defaultView.scrollX,y:r.top+this.ownerDocument.defaultView.scrollY,width:r.width,height:r.height,scale:1}}');
  const nativeBox=await viewer.evaluate(ui,"(()=>{const e=view.doc.querySelector('#cssorder'),r=e.getBoundingClientRect(),f=view.frame.getBoundingClientRect();return {x:f.left+view.frame.clientLeft+r.left,y:f.top+view.frame.clientTop+r.top,width:r.width,height:r.height,scale:1}})()");
  await c.cdp.send('Target.activateTarget',{targetId:c.activeTabId});await wait(100);const hostPNG=(await c.cdp.send('Page.captureScreenshot',{format:'png',clip:box,captureBeyondViewport:false},c.cdp.tabs.get(c.activeTabId))).data;await viewer.send('Target.activateTarget',{targetId:ui});await wait(100);const nativePNG=(await viewer.send('Page.captureScreenshot',{format:'png',clip:nativeBox,captureBeyondViewport:false},us)).data;
  if(process.env.SEEK_MIRROR_TEST_ARTIFACTS){await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'fidelity-host-paragraph.png'),Buffer.from(hostPNG,'base64'));await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'fidelity-native-paragraph.png'),Buffer.from(nativePNG,'base64'));}
  const uiSocket=new Socket();c.addClient(uiSocket);c.mirrorClients.add(uiSocket);await c.mirror.add(uiSocket);let richCursor=messages().length;await viewer.evaluate(ui,"window.out=[];window.richRoot=view.doc.querySelector('#rich');richRoot.focus();view.setSelection(richRoot,{start:2,end:2})");
  await viewer.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'},us);await viewer.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13},us);
  const richCommands=await viewer.evaluate(ui,"out.filter(m=>m.type==='mrich')");assert.equal(richCommands.length,1);assert.equal(richCommands[0].inputType,'insertParagraph');for(const command of richCommands)await c._onMessage(JSON.stringify(command),uiSocket);await until(()=>messages().slice(richCursor).some(m=>m.type==='mirror-rich'),'canonical paragraph');for(const packet of [...uiSocket.messages.filter(m=>m.type==='mirror-ack'),...messages().slice(richCursor)])await sendUI(packet);uiSocket.messages=[];
  assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#rich')===richRoot"),true);assert.equal(await viewer.evaluate(ui,"richRoot.innerHTML"),await c.cdp.evaluate(c.activeTabId,"document.querySelector('#rich').innerHTML"));checks++;
  richCursor=messages().length;await viewer.evaluate(ui,"(()=>{window.out=[];richRoot.focus();const s=view.doc.getSelection();s.selectAllChildren(richRoot);s.collapseToEnd()})()");await viewer.send('Input.insertText',{text:'Pasted words'},us);const textCommands=await viewer.evaluate(ui,"out.filter(m=>m.type==='mrich')");assert.equal(textCommands.length,1);for(const command of textCommands)await c._onMessage(JSON.stringify(command),uiSocket);await until(()=>messages().slice(richCursor).some(m=>m.type==='mirror-rich'),'canonical rich insertion');for(const packet of [...uiSocket.messages.filter(m=>m.type==='mirror-ack'),...messages().slice(richCursor)])await sendUI(packet);uiSocket.messages=[];assert.equal(await viewer.evaluate(ui,'richRoot.textContent'),await c.cdp.evaluate(c.activeTabId,"document.querySelector('#rich').textContent"));checks++;
  richCursor=messages().length;await viewer.evaluate(ui,"(()=>{window.out=[];richRoot.focus();const s=view.doc.getSelection();s.selectAllChildren(richRoot);s.collapseToEnd()})()");await viewer.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Backspace',code:'Backspace',windowsVirtualKeyCode:8},us);await viewer.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Backspace',code:'Backspace',windowsVirtualKeyCode:8},us);const deleteCommands=await viewer.evaluate(ui,"out.filter(m=>m.type==='mrich'||m.type==='mkey')");assert.equal(deleteCommands.length,1);assert.equal(deleteCommands[0].inputType,'deleteContentBackward');await c._onMessage(JSON.stringify(deleteCommands[0]),uiSocket);await until(()=>messages().slice(richCursor).some(m=>m.type==='mirror-rich'),'canonical rich delete');for(const packet of [...uiSocket.messages.filter(m=>m.type==='mirror-ack'),...messages().slice(richCursor)])await sendUI(packet);uiSocket.messages=[];assert.equal(await viewer.evaluate(ui,'richRoot.textContent'),await c.cdp.evaluate(c.activeTabId,"document.querySelector('#rich').textContent"));checks++;
  const beforeBurst=await viewer.evaluate(ui,'richRoot.textContent');await viewer.evaluate(ui,"(()=>{window.out=[];richRoot.focus();const s=view.doc.getSelection();s.selectAllChildren(richRoot);s.collapseToEnd()})()");for(const text of ['a','b','c'])await viewer.send('Input.insertText',{text},us);assert.equal((await viewer.evaluate(ui,"out.filter(m=>m.type==='mrich')")).length,1);for(let i=0;i<3;i++){richCursor=messages().length;const command=(await viewer.evaluate(ui,"out.filter(m=>m.type==='mrich')"))[i];if(!command){assert.equal(i,2,'characters typed during an edit go out together');break;}await c._onMessage(JSON.stringify(command),uiSocket);await until(()=>messages().slice(richCursor).some(m=>m.type==='mirror-rich'),'queued rich character');for(const packet of [...uiSocket.messages.filter(m=>m.type==='mirror-ack'),...messages().slice(richCursor)])await sendUI(packet);uiSocket.messages=[];}assert.equal(await viewer.evaluate(ui,'richRoot.textContent'),beforeBurst+'abc');assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#rich').textContent"),beforeBurst+'abc');checks++;
  await viewer.evaluate(ui,"(()=>{window.out=[];const n=view.doc.querySelector('#multiline');n.focus();n.setSelectionRange(4,4)})()");await viewer.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'},us);await viewer.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13},us);for(const command of await viewer.evaluate(ui,"out.filter(m=>m.type==='mkey'||m.type==='minput')"))await c._onMessage(JSON.stringify(command),uiSocket);assert.equal(await c.cdp.evaluate(c.activeTabId,"document.querySelector('#multiline').value"),'Line\n');checks++;
  const pixelCode=`(async()=>{const images=await Promise.all(${JSON.stringify([hostPNG,nativePNG])}.map(s=>createImageBitmap(new Blob([Uint8Array.from(atob(s),c=>c.charCodeAt(0))],{type:'image/png'}))));const arrays=images.map(i=>{const c=document.createElement('canvas');c.width=i.width;c.height=i.height;c.getContext('2d').drawImage(i,0,0);return c.getContext('2d').getImageData(0,0,i.width,i.height).data});let changed=0;for(let i=0;i<arrays[0].length;i+=4)if(Math.max(...[0,1,2].map(k=>Math.abs(arrays[0][i+k]-arrays[1][i+k])))>20)changed++;const sizes=images.map(i=>[i.width,i.height]);images.forEach(i=>i.close());return {sizes,changedFraction:changed/(arrays[0].length/4)}})()`;
  const pixelComparison=await viewer.evaluate(ui,pixelCode);assert.deepEqual(pixelComparison.sizes[0],pixelComparison.sizes[1]);assert.ok(pixelComparison.changedFraction<.03,JSON.stringify(pixelComparison));checks++;comparisons.push({viewport:'desktop',geometry:hostGeometry,pixels:pixelComparison});
  if(process.env.SEEK_MIRROR_TEST_ARTIFACTS){await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'fidelity-host-paragraph.png'),Buffer.from(hostPNG,'base64'));await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'fidelity-native-paragraph.png'),Buffer.from(nativePNG,'base64'));}
  await viewer.evaluate(ui,"view.frame.contentDocument.querySelector('#tap').click();const n=view.frame.contentDocument.querySelector('#message');n.focus();n.value='client edit';n.dispatchEvent(new Event('input',{bubbles:true}));");
  const outgoing=await viewer.evaluate(ui,'window.out');check(()=>assert.ok(outgoing.some(m=>m.type==='mtap')));check(()=>assert.ok(outgoing.some(m=>m.type==='minput'&&m.ins==='client edit')));
  await viewer.evaluate(ui,"window.originalField=view.doc.querySelector('#message');originalField.focus();originalField.setSelectionRange(3,3)");
  await sendUI(c.mirror.resetMessage());assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#message')===originalField&&view.doc.activeElement===originalField&&originalField.value==='client edit'"),true);checks++;
  const original=find(c.mirror.tree,'message'),parent=c.mirror.nodes.get(original.i).parent,before=find(c.mirror.tree,'email').i;
  await sendUI({type:'mirror-ops',epoch:c.mirror.epoch,ops:[{op:'remove',id:original.i},{op:'insert',parent,before,node:{...original,i:90001}}]});assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#message')===originalField&&view.doc.activeElement===originalField"),true);checks++;
  await sendUI({type:'mirror-ops',epoch:c.mirror.epoch,ops:[{op:'viewport',viewport:{w:700,h:250}}]});assert.equal(await viewer.evaluate(ui,'view.doc.activeElement===originalField'),true);checks++;
  const islandId=find(c.mirror.tree,'island').i;await c.cdp.send('DOM.scrollIntoViewIfNeeded',{nodeId:islandId},c.cdp.tabs.get(c.activeTabId));await input('mvisible',0,{ids:[islandId]});await until(()=>messages().some(m=>m.type==='mirror-islands'),'island update');checks++;
  await sendUI(messages().findLast(m=>m.type==='mirror-islands'));assert.deepEqual(await viewer.evaluate(ui,'window.fail'),[]);checks++;
  const region=messages().findLast(m=>m.type==='mirror-islands');assert.equal(region.mime,'image/png');assert.ok(region.crop.w<region.viewport.w);assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#island').localName"),'canvas');checks++;
  const childIsland=find(find(c.mirror.tree,'cross').d,'nestedIsland').i;await c.mirror.frameBridge.geometry(child,true);await input('mvisible',0,{ids:[childIsland]});await until(()=>messages().some(m=>m.type==='mirror-islands'&&m.rects.some(r=>r.id===childIsland)),'cross-frame raster crop');const childRegion=messages().findLast(m=>m.type==='mirror-islands'&&m.rects.some(r=>r.id===childIsland));await sendUI(childRegion);assert.deepEqual(await viewer.evaluate(ui,"[...view.doc.querySelector('#cross').contentDocument.querySelector('canvas').getContext('2d').getImageData(5,5,1,1).data]"),[255,0,0,255]);assert.equal(await viewer.evaluate(ui,"view.doc.querySelector('#cross').contentDocument.querySelector('canvas').getContext('2d').getImageData(20,30,1,1).data[3]"),0);assert.ok(!JSON.stringify(messages()).includes('FIXTURE_FRAME_SECRET'));checks++;
  await input('mhover',find(c.mirror.tree,'tap').i,{rx:.5,ry:.5});await until(()=>messages().some(m=>m.type==='mirror-state'&&m.rows.some(r=>r.id===find(c.mirror.tree,'tap').i&&r.hover)),'host hover state');await sendUI(messages().findLast(m=>m.type==='mirror-state'));assert.equal(await viewer.evaluate(ui,"getComputedStyle(view.doc.querySelector('#tap')).outlineWidth"),'3px');checks++;
  await until(()=>messages().some(m=>m.type==='mirror-layout'),'layout measurements');const layout=messages().findLast(m=>m.type==='mirror-layout');const repairId=layout.rows.find(r=>r.style['font-size']&&r.id===find(c.mirror.tree,'tap').i)?.id;if(repairId){await input('mlayout',0,{ids:[repairId]});await until(()=>messages().some(m=>m.type==='mirror-ops'&&m.ops.some(op=>op.op==='computed'&&op.id===repairId)),'targeted style repair');checks++;}
  c._removeClient(uiSocket);const stale=c.mirror.epoch;await c.setViewport('fit',{width:720,height:640});await until(()=>c.mirror.viewport.w===720,'outer CSS viewport includes scrollbar space');assert.equal(c.mirror.viewport.w,720);checks++;
  await c.handBack();assert.equal(c.mirror,null);assert.equal(c.viewportMode,'desktop');await c._onMessage(JSON.stringify({type:'minput',epoch:stale,id:find(reset.tree,'message').i,seq:100,at:0,del:6,ins:'stale'}),ws);assert.equal(await c.cdp.evaluate(c.activeTabId,'document.querySelector("#message").value'),'native');checks++;
  await c.navigate(base+'/captcha');await c.takeControl();await until(()=>messages().some(m=>m.type==='mirror-off'&&m.reason==='captcha'),'captcha fallback');checks++;
  assert.equal(c.status.error,null);checks++;
  // Exercise the real Work sheet over its WebSocket, including native default and the toggle.
  await c.handBack();await c.navigate(base);const sheet=await viewer.newTab(base+'/sheet');await until(()=>viewer.evaluate(sheet,'!!window.SeekBrowser'),'Work sheet module');
  const sheetSession=viewer.tabs.get(sheet);await viewer.send('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false},sheetSession);
  await viewer.evaluate(sheet,'SeekBrowser.open({control:true})');await until(()=>viewer.evaluate(sheet,"document.querySelector('#bv-stage').classList.contains('native')&&!!document.querySelector('.bv-mirror').contentDocument?.querySelector('h1')"),'Native Work sheet');checks++;
  const sizes=()=>viewer.evaluate(sheet,"(()=>{const s=document.querySelector('#bv-stage').getBoundingClientRect(),e=document.querySelector('.bv-mirror'),f=e.getBoundingClientRect();return {w:s.width,h:s.height,fw:f.width,fh:f.height,dw:parseFloat(e.style.width)}})()");
  await until(async()=>{const s=await sizes();return s.w===1600&&Math.abs(s.fw-s.w)<1&&Math.abs(s.fh-s.h)<1;},'takeover fills the window and host follows');checks++;
  assert.ok((await sizes()).h>850,JSON.stringify(await sizes()));assert.equal(await viewer.evaluate(sheet,"document.querySelector('.bv-shell').getAttribute('aria-modal')"),'true');checks++;
  assert.equal(await viewer.evaluate(sheet,"getComputedStyle(document.querySelector('#bv-canvas')).display"),'none');checks++;
  if(process.env.SEEK_MIRROR_TEST_ARTIFACTS)await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'takeover-full.jpg'),Buffer.from(await viewer.screenshot(sheet,{format:'jpeg',quality:80}),'base64'));
  await viewer.evaluate(sheet,"window.takeoverField=document.querySelector('.bv-mirror').contentDocument.querySelector('#message');takeoverField.focus();takeoverField.setSelectionRange(2,2);document.querySelector('#bv-layout').click()");
  await until(async()=>{const s=await sizes();return s.w===779&&s.dw===s.w&&c.fitSize.width===s.w&&Math.abs(s.fw-s.w)<1;},'Dock keeps the host matched');checks++;
  assert.equal(await viewer.evaluate(sheet,"document.querySelector('.bv-mirror').contentDocument.activeElement===takeoverField&&takeoverField.selectionStart===2"),true);checks++;
  if(process.env.SEEK_MIRROR_TEST_ARTIFACTS)await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'takeover-docked.jpg'),Buffer.from(await viewer.screenshot(sheet,{format:'jpeg',quality:80}),'base64'));
  await viewer.evaluate(sheet,"document.querySelector('#bv-layout').click()");await until(async()=>{const s=await sizes();return s.w===1600&&Math.abs(s.fw-s.w)<1;},'Expand restores the full window');checks++;
  assert.equal(await viewer.evaluate(sheet,"document.querySelector('#bv-view').textContent"),'Native');checks++;
  await viewer.evaluate(sheet,"document.querySelector('#bv-view').click()");await until(()=>viewer.evaluate(sheet,"document.querySelector('#bv-view').textContent==='Picture'&&!document.querySelector('#bv-canvas').hidden"),'Picture toggle');checks++;
  await viewer.evaluate(sheet,"document.querySelector('#bv-view').click()");await until(()=>viewer.evaluate(sheet,"document.querySelector('#bv-view').textContent==='Native'"),'Native toggle');checks++;
  await c.handBack();await until(()=>viewer.evaluate(sheet,"!document.querySelector('#bv-stage').classList.contains('native')"),'hand back hides Native');checks++;
  assert.equal(await viewer.evaluate(sheet,"document.querySelector('#bv-sheet').classList.contains('expanded')"),false);assert.equal(c.viewportMode,'desktop');checks++;
  assert.equal(await viewer.evaluate(sheet,"SeekBrowser.status().control==='idle'&&!document.querySelector('#bv-main').hidden&&document.querySelector('#bv-main').textContent==='Take control'"),true);checks++;
  await viewer.send('Emulation.setDeviceMetricsOverride',{width:1024,height:768,deviceScaleFactor:1,mobile:false},sheetSession);await viewer.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5},sheetSession);await viewer.evaluate(sheet,"document.querySelector('#bv-main').click()");
  await until(async()=>{const s=await sizes();return c.viewportMode==='fit'&&s.w===1024&&s.dw===1024;},'touch tablet gets the full width');assert.equal(await viewer.evaluate(sheet,"matchMedia('(pointer:coarse)').matches"),true);checks++;
  await c.handBack();await viewer.send('Emulation.setTouchEmulationEnabled',{enabled:false},sheetSession);
  await viewer.send('Emulation.setDeviceMetricsOverride',{width:393,height:844,deviceScaleFactor:1,mobile:false},sheetSession);await viewer.evaluate(sheet,'SeekBrowser.open({control:true})');
  await until(async()=>{const s=await sizes();return c.viewportMode==='mobile'&&c.mirror?.ready&&s.w===393&&s.dw===393&&Math.abs(s.fw-s.w)<1&&await viewer.evaluate(sheet,"!!document.querySelector('.bv-mirror').contentDocument?.querySelector('#message')");},'phone uses the entire width');checks++;
  const phoneNode=c.mirror.nodes.get(find(c.mirror.tree,'cssorder').i).node,phoneHost=await c.mirror.local(phoneNode,geometryFunction),phoneNative=await viewer.evaluate(sheet,'('+geometryFunction+').call(document.querySelector(".bv-mirror").contentDocument.querySelector("#cssorder"))');assert.deepEqual(phoneNative,phoneHost);comparisons.push({viewport:'phone',geometry:phoneHost});checks++;
  if(process.env.SEEK_MIRROR_TEST_ARTIFACTS)await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'takeover-phone.jpg'),Buffer.from(await viewer.screenshot(sheet,{format:'jpeg',quality:80}),'base64'));
  await viewer.evaluate(sheet,"window.phoneField=document.querySelector('.bv-mirror').contentDocument.querySelector('#message');phoneField.focus();Object.defineProperty(visualViewport,'height',{value:440,configurable:true});Object.defineProperty(visualViewport,'offsetTop',{value:120,configurable:true});visualViewport.dispatchEvent(new Event('resize'))");
  await until(()=>viewer.evaluate(sheet,"Math.abs(document.querySelector('#bv-sheet').getBoundingClientRect().height-440)<1&&Math.abs(document.querySelector('#bv-sheet').getBoundingClientRect().top-120)<1"),'visible viewport keyboard size');checks++;
  await until(async()=>Math.abs(c.mobileSize.height-(await sizes()).h)<1,'phone host follows keyboard stage');checks++;
  assert.equal(await viewer.evaluate(sheet,"document.querySelector('.bv-mirror').contentDocument.activeElement===phoneField"),true);checks++;
  await viewer.evaluate(sheet,"delete visualViewport.height;delete visualViewport.offsetTop;visualViewport.dispatchEvent(new Event('resize'))");await c.handBack();
  await viewer.closeTab(sheet);await c.navigate(base);await c.takeControl();await until(()=>c.mirror?.ready,'popup test mirror');const parentTab=c.activeTabId;await input('mtap',find(c.mirror.tree,'popup').i,{rx:.5,ry:.5});await c._refreshStatus();await until(()=>c.activeTabId!==parentTab&&c.mirror?.ready,'new popup followed');assert.equal(c.tabOwners.get(c.activeTabId),c.agentOwner||undefined);checks++;
  const popupTab=c.activeTabId;await c.tab({action:'switch',tabId:parentTab});await until(()=>c.mirror?.ready&&!!find(c.mirror.tree,'cross')?.d,'cross-site capture after tab return');assert.equal(c.activeTabId,parentTab);checks++;await c.tab({action:'close',tabId:popupTab});await until(()=>c.mirror?.ready,'mirror after close');assert.ok(!(await c.listTabs()).tabs.some(t=>t.id===popupTab));checks++;
  await c.setViewport('fit',{width:900,height:700,dpr:2,colorScheme:'dark',reducedMotion:true,coarse:true});assert.deepEqual(await c.cdp.evaluate(c.activeTabId,"[devicePixelRatio,matchMedia('(prefers-color-scheme:dark)').matches,matchMedia('(prefers-reduced-motion:reduce)').matches,matchMedia('(pointer:coarse)').matches]"),[2,true,true,true]);checks++;await c.handBack();assert.equal(await c.cdp.evaluate(c.activeTabId,'devicePixelRatio'),1);assert.equal(await c.cdp.evaluate(c.activeTabId,"matchMedia('(pointer:coarse)').matches"),false);checks++;
  await c.takeControl();await until(()=>c.mirror?.ready,'mirror after control');const active=c.mirror;await active.enqueue(()=>{throw new Error('PRIVATE_MIRROR_DETAIL');});assert.equal(c.status.error,null);assert.ok(!JSON.stringify(ws.messages).includes('PRIVATE_MIRROR_DETAIL'));checks++;
  const chrome=await c.cdp.send('Browser.getVersion');if(process.env.SEEK_MIRROR_TEST_ARTIFACTS)await writeFile(join(process.env.SEEK_MIRROR_TEST_ARTIFACTS,'fidelity-comparison.json'),JSON.stringify({chrome:chrome.product,comparisons,checks},null,2));
}catch(e){console.error(e);console.error('Mirror fallback reasons:',messages().filter(m=>m.type==='mirror-off').map(m=>m.reason));console.error('Fixture capture state:',{fit:c.fitSize,viewport:c.mirror?.viewport,pending:[...c.mirror?.fixturePending||[]],visualPending:c.cdp?.visualCalls.size,children:[...c.mirror?.frameBridge?.children.values()||[]].map(v=>({ready:v.ready,pending:[...v.fixturePending||[]]}))});if(c.running){const tab=(await viewer.listTabs()).find(t=>t.url===base+'/sheet');if(tab)console.error('Sheet state:',await viewer.evaluate(tab.id,"({control:SeekBrowser.status().control,mirror:SeekBrowser.status().mirror,native:document.querySelector('#bv-stage').classList.contains('native'),quality:document.querySelector('#bv-quality').textContent,stage:document.querySelector('#bv-stage').clientWidth,frame:document.querySelector('.bv-mirror').style.width,expanded:document.querySelector('#bv-sheet').classList.contains('expanded')})"));}process.exitCode=1;}finally{await viewer.close();await c.close();wss.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
console.log('Mirror browser checks: '+checks);




