import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CapabilityRegistry,objectSchema} from '../lib/work-capabilities.js';
import {validateRecipe} from '../lib/work-workflows.js';
import {WorkflowStore} from '../lib/work-workflow-store.js';
import {WorkflowRunner} from '../lib/work-workflow-runner.js';
const input=objectSchema({target:{type:'integer',minimum:0,maximum:100}},['target']),output=input;
const recipe={id:'fixture_cart',version:1,title:'Fixture cart',input,steps:[{id:'set',capability:'fixture.set',version:1,input:{$ref:'input'}}],result:'set'};
async function fixture(options={}){
 const dir=await mkdtemp(join(tmpdir(),'seek-wf-run-')),clock={now:Date.now()},state={target:0,writes:0},task={id:'fixture-task',status:'running'};
 const registry=new CapabilityRegistry().register({name:'fixture.set',version:1,effect:'write',resource:'fixture-cart',input,output,timeoutMs:options.timeoutMs||1000,lockKey:()=> 'fixture:cart',execute:async a=>{state.target=a.target;state.writes++;await options.execute?.();return {...a};},verify:r=>r.target===state.target,reconcile:async a=>state.target===a.target?{...a}:undefined});
 const store=new WorkflowStore(dir,{now:()=>clock.now});store.put(validateRecipe(recipe,registry));const run=store.create(task.id,'once',recipe,{target:3});
 const context={task,fixture:true,writeBroker:async(d,a,execute)=>execute()};const runner=new WorkflowRunner(registry,store,{hook:options.hook});return {state,task,registry,store,runner,context,run,clock,dir};
}
test('duplicate submissions and concurrent execution write once',async()=>{const f=await fixture();try{assert.equal(f.store.create(f.task.id,'once',recipe,{target:3}).id,f.run.id);assert.throws(()=>f.store.create(f.task.id,'once',recipe,{target:4}));const r=await Promise.all([f.runner.run(f.run.id,f.context),f.runner.run(f.run.id,f.context)]);assert.ok(r.every(x=>x.state==='succeeded'));assert.equal(f.state.writes,1);await f.runner.run(f.run.id,f.context);assert.equal(f.state.writes,1);}finally{f.store.close();}});
test('lost return after provider commit reconciles instead of repeating write',async()=>{let injected=false;const f=await fixture({hook:phase=>{if(phase==='after-return'&&!injected){injected=true;throw new Error('Lost connection');}}});try{let r=await f.runner.run(f.run.id,f.context);assert.equal(r.state,'uncertain');f.store.resume(r.id);r=await new WorkflowRunner(f.registry,f.store).run(r.id,f.context);assert.equal(r.state,'succeeded');assert.equal(f.state.writes,1);}finally{f.store.close();}});
test('unresolved dispatch remains uncertain and never retries the provider',async()=>{const f=await fixture({hook:phase=>{if(phase==='before-dispatch')throw new Error('Interrupted before network');}});try{let r=await f.runner.run(f.run.id,f.context);assert.equal(r.state,'uncertain');assert.equal(f.state.writes,0);f.store.resume(r.id);r=await new WorkflowRunner(f.registry,f.store).run(r.id,f.context);assert.equal(r.state,'uncertain');assert.equal(f.state.writes,0);}finally{f.store.close();}});
test('cancel midflight prevents success and late checkpoints; recovery verifies provider state',async()=>{
 let release,started;const gate=new Promise(r=>release=r),seen=new Promise(r=>started=r);const f=await fixture({execute:async()=>{started();await gate;}});
 try{const pending=f.runner.run(f.run.id,f.context);await seen;f.runner.cancel(f.run.id);release();const r=await pending;assert.equal(r.state,'uncertain');assert.notEqual(r.steps[0].state,'verified');f.store.resume(r.id);assert.equal((await new WorkflowRunner(f.registry,f.store).run(r.id,f.context)).state,'succeeded');assert.equal(f.state.writes,1);}finally{f.store.close();}
});
test('write deadlines leave uncertainty rather than replay',async()=>{const f=await fixture({timeoutMs:10,execute:()=>new Promise(()=>{})});try{assert.equal((await f.runner.run(f.run.id,f.context)).state,'uncertain');assert.equal(f.state.writes,1);}finally{f.store.close();}});
test('missing broker, inactive task, eval account reads and proactive writes are denied',async()=>{const f=await fixture();try{for(const context of [{task:f.task},{...f.context,task:{...f.task,status:'stopped'}},{...f.context,task:{...f.task,eval:{}},fixture:false},{...f.context,task:{...f.task,proactive:{}}}])await assert.rejects(f.runner.run(f.run.id,context),/broker|active|accounts|Preparation/);assert.equal(f.state.writes,0);}finally{f.store.close();}});
test('live leases fence competing runners; expired owners lose checkpoint rights',async()=>{const f=await fixture();try{const lease=f.store.claim(f.run.id,'old',100);assert.equal((await new WorkflowRunner(f.registry,f.store).run(f.run.id,f.context)).state,'running');f.clock.now+=101;assert.equal((await f.runner.run(f.run.id,f.context)).state,'succeeded');assert.throws(()=>f.store.step(f.run.id,'old',lease.epoch,'set','verified',{output:{target:3}}),/lease/);assert.equal(f.state.writes,1);}finally{f.store.close();}});
test('resource locks block conflicting writes until uncertainty is reconciled',async()=>{const f=await fixture({hook:phase=>{if(phase==='after-return')throw new Error('lost');}});try{assert.equal((await f.runner.run(f.run.id,f.context)).state,'uncertain');const other=f.store.create('other','once',recipe,{target:4}),r=await new WorkflowRunner(f.registry,f.store).run(other.id,{...f.context,task:{id:'other',status:'running'}});assert.equal(r.error.code,'resource_busy');assert.equal(f.state.writes,1);}finally{f.store.close();}});
test('version immutability, disabled admission and cross-task ownership',async()=>{const f=await fixture();try{assert.throws(()=>f.store.put(validateRecipe({...recipe,title:'Changed'},f.registry)),/cannot be edited/);await assert.rejects(f.runner.run(f.run.id,{...f.context,task:{id:'other',status:'running'}}),/another task/);f.store.setState(recipe.id,1,'disabled');await assert.rejects(f.runner.run(f.run.id,f.context),/disabled/);}finally{f.store.close();}});
