import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CdpBrowser} from '../lib/cdp.js';
import {ready} from '../../../experiments/calendar-20261006/mount.mjs';
test('workflow navigation, failure recovery and guided forms work on desktop and phones',async()=>{
 const m=await ready,ui=new CdpBrowser({headless:true,userDataDir:await mkdtemp(join(tmpdir(),'seek-workflow-ui-')),windowSize:'1440,1000'}),errors=[];
 const wait=async(tab,expression)=>{const deadline=Date.now()+12000;while(Date.now()<deadline){if(await ui.evaluate(tab,expression))return;await new Promise(r=>setTimeout(r,40));}throw new Error('UI timed out: '+expression);};
 const action=(tab,code)=>ui.evaluate(tab,code+';true');
 const screenshot=async(tab,name)=>{if(process.env.SEEK_WORKFLOW_UX_OUTPUT){await mkdir(process.env.SEEK_WORKFLOW_UX_OUTPUT,{recursive:true});await writeFile(join(process.env.SEEK_WORKFLOW_UX_OUTPUT,name+'.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));}};
 try{
  await ui.launch();const tab=await ui.newTab('about:blank'),session=ui.tabs.get(tab);await ui.send('Runtime.enable',{},session);ui.onEvent(session,'Runtime.exceptionThrown',event=>errors.push(event.exceptionDetails?.text||'exception'));
  let blockCatalog=true;await ui.send('Fetch.enable',{patterns:[{urlPattern:m.base+'/work/api/workflows',requestStage:'Request'}]},session);
  ui.onEvent(session,'Fetch.requestPaused',event=>{void ui.send(blockCatalog?'Fetch.fulfillRequest':'Fetch.continueRequest',blockCatalog?{requestId:event.requestId,responseCode:503,responseHeaders:[{name:'Content-Type',value:'application/json'}],body:Buffer.from('{"error":"Fixture temporarily unavailable"}').toString('base64')}:{requestId:event.requestId},session).catch(error=>errors.push(error.message));});
  await ui.navigate(tab,m.base+'/work?view=workflows');await wait(tab,"!!document.querySelector('[data-workflow-retry]')");
  assert.equal(await ui.evaluate(tab,"document.querySelector('.side-nav [data-view=workflows]').getAttribute('aria-current')"),'page');
  assert.equal(await ui.evaluate(tab,"document.querySelector('[data-workflow=cpu-calendar]').disabled"),true,'unavailable catalog cannot be run');
  assert.equal(await ui.evaluate(tab,"document.querySelector('[data-workflow=email-draft]').disabled"),false,'saved prompts survive a CPU catalog failure');
  blockCatalog=false;await action(tab,"document.querySelector('[data-workflow-retry]').click()");await wait(tab,"document.querySelector('[data-workflow=cpu-calendar]')?.disabled===false");await ui.send('Fetch.disable',{},session);
  assert.equal(await ui.evaluate(tab,"document.querySelector('#main').textContent.includes('Ready to run')&&document.querySelector('#main').textContent.includes('Start with Seek')"),true);
  await screenshot(tab,'workflow-desktop');
  await action(tab,"document.querySelector('[data-view=tasks]').click()");await ui.navigate(tab,m.base+'/work?view=workflows');await wait(tab,"document.querySelector('[data-workflow=cpu-calendar]')?.disabled===false");
  await action(tab,"document.querySelector('[data-workflow=cpu-calendar]').click()");await wait(tab,"!!document.querySelector('#workflow-use [name=from]')");
  assert.equal(await ui.evaluate(tab,"document.querySelector('[name=from]').type"),'datetime-local');
  assert.equal(await ui.evaluate(tab,"!!document.querySelector('[name=from]').value"),true);await screenshot(tab,'workflow-calendar');
  await action(tab,"document.querySelector('[name=from]').value='2026-10-09T09:00';document.querySelector('[name=to]').value='2026-10-09T08:00';document.querySelector('#workflow-use').requestSubmit()");
  await wait(tab,"!document.querySelector('#workflow-form-error').hidden");assert.match(await ui.evaluate(tab,"document.querySelector('#workflow-form-error').textContent"),/after the start/);assert.equal(await ui.evaluate(tab,"document.activeElement.name"),'to');
  await action(tab,"document.querySelector('[name=to]').value='2026-10-09T17:00';document.querySelector('#workflow-use').requestSubmit()");
  await wait(tab,"document.querySelector('#main').textContent.includes('480 minutes free')");
  assert.equal(await ui.evaluate(tab,"document.querySelector('#product-dialog').open"),false);assert.equal(await ui.evaluate(tab,"document.querySelector('#main').textContent.includes('Calendar availability')"),true);
  assert.match(await ui.evaluate(tab,'location.search'),/task=/);
  await ui.send('Emulation.setDeviceMetricsOverride',{width:375,height:812,deviceScaleFactor:1,mobile:true},session);
  assert.equal(await ui.evaluate(tab,"document.querySelector('.bottom-bar [data-view=workflows]').getBoundingClientRect().width>0"),true);
  await action(tab,"document.querySelector('.bottom-bar [data-view=workflows]').click()");await wait(tab,"document.querySelector('[data-workflow=cpu-groceries]')?.disabled===false");await screenshot(tab,'workflow-mobile');
  await action(tab,"document.querySelector('[data-workflow=cpu-groceries]').click()");await wait(tab,"!!document.querySelector('[data-grocery-item]')");
  await action(tab,"document.querySelector('[data-grocery-example]').click()");assert.equal(await ui.evaluate(tab,"document.querySelectorAll('[data-grocery-item]').length"),2);
  await action(tab,"document.querySelectorAll('[data-grocery-remove]')[1].click();document.querySelector('[data-grocery-field=quantity]').value='3';document.querySelector('.grocery-owned').open=true;document.querySelector('[data-grocery-field=pantry]').value='1'");
  await action(tab,"document.querySelector('[data-grocery-add]').click()");assert.equal(await ui.evaluate(tab,"document.querySelectorAll('[data-grocery-item]').length"),2);await action(tab,"document.querySelectorAll('[data-grocery-remove]')[1].click()");
  assert.equal(await ui.evaluate(tab,"document.querySelector('[data-grocery-field=name]').value"),'Milk','removing a row preserves the others');
  await screenshot(tab,'workflow-groceries');
  await ui.send('Emulation.setDeviceMetricsOverride',{width:320,height:740,deviceScaleFactor:1,mobile:true},session);
  assert.equal(await ui.evaluate(tab,"document.querySelector('#product-dialog').scrollWidth<=document.querySelector('#product-dialog').clientWidth+1"),true,'small-phone form fits');
  await action(tab,"document.querySelector('#workflow-use').requestSubmit()");
  await wait(tab,"document.querySelector('#main').textContent.includes('Additions: $7.98')");assert.equal(await ui.evaluate(tab,"document.documentElement.scrollWidth<=window.innerWidth+1"),true);
  await action(tab,"document.querySelector('.bottom-bar [data-view=workflows]').click()");await wait(tab,"!!document.querySelector('[data-workflow-build]')");await action(tab,"document.querySelector('[data-workflow-build]').click()");assert.match(await ui.evaluate(tab,"document.querySelector('#prompt').value"),/task I repeat/);
  assert.equal(await ui.evaluate(tab,"!!document.querySelector('.welcome')"),true,'building starts an editable request and never sends automatically');
  const tasks=(await (await fetch(m.base+'/work/api/state')).json()).tasks;assert.equal(tasks.filter(t=>t.workflow).length,2);assert.equal(tasks.some(t=>t.sessionId),false,'guided workflows create no model session');
  assert.deepEqual(errors,[]);
 }finally{await ui.close();m.stop();}
});
