// Exercises new product flows against synthetic fixtures; never contacts a model or user account.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CdpBrowser} from '../lib/cdp.js';
import {WorkAssets} from '../lib/work-assets.js';
import {WorkUpdates,taskPage} from '../lib/work-updates.js';

test('workbench, library/revisions, typed workflows, voice, focus, steering and Finance duplicate protection',async()=>{
 let releaseTemplateRead,templateReads=0;const firstTemplateRead=new Promise(resolve=>releaseTemplateRead=resolve);
 const assets=await new WorkAssets().init(),now=Date.now(),errors=[],bodies=[],templates=[],streams=new Set();const financeRequests=[];let creates=0,backupCount=0,backupLocal=false,keyRequests=0;let devices=[{id:'this-device',identity:'owner',label:'Fixture browser',createdAt:now,lastSeenAt:now,current:true},{id:'other-device',identity:'owner',label:'Other fixture browser',createdAt:now,lastSeenAt:now,current:false}];
 const memories={settings:{enabled:false,time:'03:00',timezone:'America/Chicago'},runs:[],pending:0,running:false,counts:{active:1,review:0},lessons:[{id:'fixture-memory',text:'Use concise prose',kind:'preference',scope:'writing',status:'active',updatedAt:now,sources:[{taskId:'alpha',title:'Alpha report',quote:'Use concise prose'}]}]};
 const tasks=[{id:'alpha',title:'Alpha report',objective:'Create a sourced report',status:'complete',mode:'task',createdAt:now,updatedAt:now,messages:[{role:'user',text:'Create a report',time:now},{role:'assistant',text:'A finished fixture report.',time:now+1}],events:[],plan:[],contextUsed:[{text:'Use concise prose',scope:'personal'}],resultEvidence:{status:'verified',summary:'File checks only',checks:[{label:'Markdown is readable',status:'passed'}]},artifacts:[{id:'a1',title:'Report.md',type:'md',bytes:200,version:1,at:now},{id:'a2',title:'Report revised.md',type:'md',bytes:240,version:2,parentId:'a1',at:now+1}]},{id:'beta',title:'Beta task',objective:'Research a fixture',status:'running',mode:'task',createdAt:now,updatedAt:now,messages:[{role:'user',text:'Research a fixture',time:now}],events:[],plan:[{title:'Read sources',status:'working'}],progress:{step:2,total:5,current:'Read fixture sources',startedAt:now},artifacts:[]}];
 const engine={store:{version:1,settings:{name:'Seek',notifications:false},tasks}},updates=new WorkUpdates(engine,{health:()=>({model:'ready'})});
 const financeData={status:{connected:true,updatedAt:now},accounts:[{id:'card',name:'Fixture card',current:3500}],summary:{assets:1000,debt:3500,netWorth:-2500,monthSpend:0,monthIncome:0,monthNet:0},transactions:[],budgets:[],categories:[],budgetCategories:[],cashflowMonths:[],balanceHistory:[],recurring:[],investmentHoldings:[],liabilities:{credit:[{account_id:'card',minimum_payment_amount:25.99,last_statement_balance:3000}]}};
 const server=createServer(async(req,res)=>{
  const url=new URL(req.url,'http://local'),json=value=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};
  const read=async()=>{let text='';for await(const c of req)text+=c;return JSON.parse(text||'{}');};
  if(url.pathname==='/work/finance.js'){financeRequests.push(url.search);if(!url.searchParams.has('retry')){res.writeHead(503,{'Content-Type':'text/plain'});res.end('Seek is restarting');return;}}
  if(url.pathname==='/work/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.write(`event: revision\ndata: ${updates.revision}\n\n`);streams.add(res);res.on('close',()=>streams.delete(res));return;}
  if(url.pathname==='/work/api/updates')return json(updates.changed(url.searchParams.get('since')));
  if(url.pathname==='/work/api/task'&&req.method==='GET')return json(taskPage(tasks.find(t=>t.id===url.searchParams.get('id'))));
  if(url.pathname==='/work/api/task'&&req.method==='POST'){const body=await read();bodies.push(body);creates++;await new Promise(r=>setTimeout(r,100));const task={id:'created-'+creates,title:body.objective.slice(0,60),objective:body.objective,domain:body.domain,status:'queued',createdAt:now,updatedAt:Date.now(),messages:[{role:'user',text:body.objective,time:Date.now()}],artifacts:[],events:[],plan:[]};tasks.push(task);updates.refresh();return json(task);}
  if(url.pathname==='/work/api/task/update'){const body=await read(),task=tasks.find(t=>t.id===body.id);Object.assign(task,body);updates.refresh();return json(taskPage(task));}
  if(url.pathname==='/work/api/control'){const body=await read(),task=tasks.find(t=>t.id===body.id);bodies.push(body);if(body.action==='reply'){task.messages.push({role:'user',text:body.answer,time:Date.now()});task.deliveries=[{id:'delivery',text:body.answer,receivedAt:Date.now(),status:'received'}];}updates.refresh();return json(taskPage(task));}
  if(url.pathname==='/work/api/templates'){
   if(req.method==='POST'){const body=await read();if(body.action==='remove')templates.splice(templates.findIndex(t=>t.id===body.id),1);else templates.push({id:'saved-workflow',...body});releaseTemplateRead();return json({items:templates});}
   const snapshot=structuredClone(templates);if(++templateReads===1)await firstTemplateRead;return json({items:snapshot});
  }
  if(url.pathname==='/work/api/library/search')return json({query:url.searchParams.get('q'),hits:url.searchParams.get('q')==='hidden phrase'?[{taskId:'alpha',id:tasks[0].artifacts[0].id,excerpt:'…the <hidden phrase> inside…'}]:[]});
  if(url.pathname==='/work/api/search')return json({tasks:[{id:'alpha',title:'Alpha report',excerpt:'Fixture result containing evidence'}],artifacts:[],memories:[]});
  if(url.pathname==='/work/api/desktop')return json({computers:[{id:'fixture-mac',name:'Studio Mac',verified:true,remoteGrant:true,online:true,state:'human'}]});
  if(url.pathname==='/work/api/subagents')return json({children:[]});
  if(url.pathname==='/work/api/account')return json({vault:{state:'missing'},sites:[],always:[]});
  if(url.pathname==='/work/api/dreaming')return json(memories);
  if(url.pathname==='/work/api/dreaming/memory'){const body=await read();bodies.push(body);if(body.action==='edit'){const lesson=memories.lessons.find(l=>l.id===body.id);lesson.revisions=[{text:lesson.text,project:lesson.project,person:lesson.person,updatedAt:lesson.updatedAt}];Object.assign(lesson,body);}return json(memories);}
  if(url.pathname==='/work/api/backups')return json({encrypted:true,lastAt:backupCount?now:null,files:backupCount?3:undefined,canConfigure:backupLocal});
  if(url.pathname==='/work/api/backups/create'){backupCount++;return json({name:'fixture.seekbackup',files:3});}
  if(url.pathname==='/work/api/backups/recovery-key'){assert.equal(backupLocal,true,'Public UI must never request the local recovery key');assert.equal(req.method,'POST');keyRequests++;return json({format:1,key:'recovery-fixture-opaque-key',keyId:'fixture-key-id',warning:'Store the key away from this PC.'});}
  if(url.pathname==='/work/api/export')return json({store:{tasks:[{id:'fixture-export'}]},exportedAt:now,secrets:'Reauthorize on another account.'});
  if(url.pathname==='/auth/api/sessions')return json({sessions:devices,csrf:'fixture-csrf'});
  if(url.pathname==='/auth/api/sessions/revoke'){const body=await read();assert.equal(body.csrf,'fixture-csrf');devices=devices.filter(d=>body.others?d.current:d.id!==body.id);return json({ok:true});}
  if(url.pathname==='/work/api/artifact'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<h1>Fixture output '+url.searchParams.get('id')+'</h1>');return;}
  if(url.pathname==='/work/api/finance/status')return json({configured:true,connected:true,canConfigure:false,connections:[],products:{liabilities:true}});
  if(url.pathname==='/work/api/finance/answers')return json({answers:tasks.filter(t=>t.domain==='finance').map(t=>({id:t.id,question:t.objective,status:t.status,activity:t.activity,answer:[...t.messages].reverse().find(m=>m.role==='assistant')?.text||null,evidence:t.financeEvidence||null}))});
  if(url.pathname==='/work/api/finance/dashboard')return json(financeData);
  if(!assets.serve(req,res,url)){res.writeHead(404,{'Content-Type':'application/json'});res.end('{"error":"Fixture route unavailable"}');}
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const ui=new CdpBrowser({headless:true,userDataDir:await mkdtemp(join(tmpdir(),'seek-product-ui-')),windowSize:'1440,1000'});
 const wait=async(tab,expression,label)=>{const deadline=Date.now()+7000;while(Date.now()<deadline){if(await ui.evaluate(tab,expression))return;await new Promise(r=>setTimeout(r,30));}throw new Error('Timed out: '+label);};
 const action=(tab,code)=>ui.evaluate(tab,code+';true');
 try{
  await ui.launch();const tab=await ui.newTab('about:blank'),session=ui.tabs.get(tab);
  await ui.send('Runtime.enable',{},session);ui.onEvent(session,'Runtime.exceptionThrown',event=>errors.push(event.exceptionDetails?.text||'exception'));
  await ui.send('Page.addScriptToEvaluateOnNewDocument',{source:`window.SpeechRecognition=class{start(){setTimeout(()=>this.onresult({resultIndex:0,results:Object.assign([{0:{transcript:'Voice fixture text'},isFinal:true}],{length:1})}),10)}stop(){this.onend?.()}};`},session);
  await ui.navigate(tab,'http://127.0.0.1:'+server.address().port+'/work');await wait(tab,"!!document.querySelector('.welcome')",'welcome');
  assert.equal(await ui.evaluate(tab,"getComputedStyle(document.querySelector('#agent-panel')).display"),'none');
  await action(tab,"document.querySelector('#voice-input').click()");await wait(tab,"document.querySelector('#prompt').value.includes('Voice fixture text')",'voice transcript');assert.equal(creates,0,'Voice must never send automatically');await action(tab,"document.querySelector('#voice-input').click()");
  await action(tab,"document.querySelector('[data-select=alpha]').click()");await wait(tab,"!!document.querySelector('.context-used')",'task context');assert.match(await ui.evaluate(tab,"document.querySelector('.result-evidence').textContent"),/File checks only/);assert.equal(await ui.evaluate(tab,"document.querySelector('#attach').hidden"),false);
  await action(tab,"document.querySelector('[data-task-pin]').click()");await wait(tab,"document.querySelector('[data-task-pin]').getAttribute('aria-pressed')==='true'",'pin');
  await action(tab,"document.querySelector('[data-view=files]').click()");await wait(tab,"document.querySelectorAll('.library-card').length===2",'library');
  await action(tab,"for(const el of document.querySelectorAll('[data-compare]')){el.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}))}document.querySelector('#compare-files').click()");assert.equal(await ui.evaluate(tab,"document.querySelectorAll('.artifact-comparison iframe').length"),2);await action(tab,"document.querySelector('#product-dialog [data-dialog-close]').click()");
  await action(tab,"document.querySelector('[data-revise=a2]').click()");await wait(tab,"document.querySelector('#attachments').textContent.includes('Revision source')",'revision source');await action(tab,"document.querySelector('#prompt').value='Make the report concise';document.querySelector('#composer').requestSubmit()");await wait(tab,"!!document.querySelector('.conversation')",'revision task');assert.deepEqual(bodies.find(b=>b.sourceArtifact)?.sourceArtifact,{taskId:'alpha',id:'a2'});
  await action(tab,"document.querySelector('[data-view=workflows]').click()");await wait(tab,"!!document.querySelector('[data-workflow=email-draft]')",'workflow catalog');await action(tab,"document.querySelector('[data-workflow=email-draft]').click();document.querySelector('[name=recipient]').value='fixture@example.com';document.querySelector('[name=instructions]').value='A polite thank you';document.querySelector('#workflow-use').requestSubmit()");assert.match(await ui.evaluate(tab,"document.querySelector('#prompt').value"),/fixture@example.com/);assert.equal(creates,1,'Template should fill composer, not submit');
  await action(tab,"document.querySelector('[data-view=workflows]').click();document.querySelector('#new-workflow').click();document.querySelector('[name=title]').value='Reusable fixture';document.querySelector('[name=objective]').value='Read {{topic}} and make a brief';document.querySelector('#workflow-edit').requestSubmit()");await wait(tab,"!!document.querySelector('[data-workflow=saved-workflow]')",'saved workflow');assert.equal(templates[0].fields[0].name,'topic');
  await action(tab,"document.querySelector('#search-work').click();document.querySelector('#workspace-query').value='evidence';document.querySelector('#workspace-query').dispatchEvent(new Event('input',{bubbles:true}))");await wait(tab,"!!document.querySelector('.search-hit')",'workspace search');await action(tab,"document.querySelector('.search-hit').click()");assert.equal(await ui.evaluate(tab,"document.querySelector('#search-dialog').open"),false);
  await action(tab,"document.querySelector('[data-select=beta]').click()");await wait(tab,"!!document.querySelector('.work-summary progress')",'measured progress');assert.equal(await ui.evaluate(tab,"document.querySelector('.work-summary progress').value"),2);
  await action(tab,"document.querySelector('#prompt').value='Add the source links';document.querySelector('#composer').requestSubmit()");await wait(tab,"document.querySelector('.steering-receipts')?.textContent.includes('Received')",'steering receipt');assert.ok(bodies.find(b=>b.action==='reply')?.requestId);
  await action(tab,"document.querySelector('[data-view=finance]').click()");await wait(tab,"!!document.querySelector('[data-fin-tab=debt]')",'finance');assert.ok(financeRequests.length>=2&&new URLSearchParams(financeRequests.at(-1)).has('retry'),'Finance module recovers from a dropped request with a fresh URL: '+JSON.stringify(financeRequests));await action(tab,"document.querySelector('[data-fin-tab=debt]').click()");assert.match(await ui.evaluate(tab,"document.querySelector('.fin-debt-amounts').textContent"),/Minimum due\$25.99/);
  await action(tab,"document.querySelector('#fin-ask input').value='Explain my card';document.querySelector('#fin-ask').requestSubmit();document.querySelector('#fin-ask').requestSubmit()");await wait(tab,"document.querySelector('.fin-answer .fin-question')?.textContent==='Explain my card'",'finance answer beside the dashboard');assert.equal(await ui.evaluate(tab,"!!document.querySelector('[data-fin-tab]')"),true,'Finance stays open after asking');
  {const asked=tasks.find(t=>t.objective==='Explain my card');Object.assign(asked,{status:'complete',updatedAt:Date.now()+2,financeEvidence:{rows:[{date:'2026-09-03',name:'Fixture Cafe',amount:12.5,currency:'USD',account:'Card ••4242'}],reports:[],queries:[{query:'card',matched:1}]}});asked.messages.push({role:'assistant',text:'Your card balance is **$3,500**.',time:Date.now()});updates.refresh();}
  await wait(tab,"document.querySelector('.fin-answer .md strong')?.textContent==='$3,500'",'finance answer text');await action(tab,"document.querySelector('.fin-evidence summary').click()");await action(tab,"document.querySelector('[data-fin-evidence]').click()");await wait(tab,"document.querySelector('[data-fin-tab=transactions]')?.classList.contains('selected')&&document.querySelector('[data-fin-query]')?.value==='Fixture Cafe'",'evidence opens matching transactions');
  await action(tab,"document.querySelector('[data-fin-open-chat]').click()");await wait(tab,"document.querySelector('.conv-title')?.textContent==='Explain my card'",'finance conversation');assert.equal(creates,2,'Finance duplicate submit must create one task');assert.ok(bodies.find(b=>b.objective==='Explain my card'&&b.domain==='finance')?.requestId);
  await action(tab,"document.querySelector('[data-view=settings]').click()");await wait(tab,"!!document.querySelector('.settings-nav [data-view=privacy]')",'settings');assert.equal(await ui.evaluate(tab,"!!document.querySelector('#memory-form')"),true,'Settings opens on the profile tab');
  await action(tab,"document.querySelector('.settings-nav [data-view=privacy]').click()");await wait(tab,"!!document.querySelector('[data-session=other-device]')",'device inventory');await action(tab,"document.querySelector('[data-session=other-device]').click()");await wait(tab,"!document.querySelector('[data-session=other-device]')",'device revocation');assert.equal(devices.length,1);
  await action(tab,"document.querySelector('.settings-nav [data-view=memory]').click()");await wait(tab,"!!document.querySelector('[data-dream-action=edit]')",'memory controls');await action(tab,"document.querySelector('[data-dream-action=edit]').click();document.querySelector('[data-dream-edit] [name=text]').value='Use short paragraphs';document.querySelector('[data-dream-edit] [name=project]').value='Fixture project';document.querySelector('[data-dream-edit] [name=owner]').checked=true;document.querySelector('[data-dream-edit]').requestSubmit()");await wait(tab,"document.querySelector('#dream-lessons').textContent.includes('Previous corrections')",'versioned memory');assert.deepEqual(bodies.find(b=>b.action==='edit'),{id:'fixture-memory',action:'edit',text:'Use short paragraphs',project:'Fixture project',person:'owner',kind:'preference',about:'self'});assert.match(await ui.evaluate(tab,"document.querySelector('#dream-lessons').textContent"),/Owner tasks · Project: Fixture project/);
  await action(tab,"document.querySelector('.settings-nav [data-view=privacy]').click()");await wait(tab,"!!document.querySelector('[data-security=backup]')",'privacy controls');
  await action(tab,"document.querySelector('[data-security=backup]').click()");await wait(tab,"document.querySelector('.workspace-safety').textContent.includes('Last encrypted backup')",'backup status');assert.equal(backupCount,1);
  await action(tab,"const original=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.download){window.exportProbe={href:this.href,name:this.download}}else original.call(this)};document.querySelector('[data-security=export]').click()");await wait(tab,"!!window.exportProbe",'export');assert.match(await ui.evaluate(tab,'window.exportProbe.name'),/^seek-work-export-/);assert.equal(await ui.evaluate(tab,"fetch(window.exportProbe.href).then(r=>r.json()).then(x=>x.store.tasks[0].id)"),'fixture-export');
  assert.equal(await ui.evaluate(tab,"!!document.querySelector('[data-security=recovery-key]')"),false,'Recovery key is unavailable through the public UI');assert.equal(keyRequests,0,'Recovery key must never be fetched automatically');backupLocal=true;await action(tab,"document.querySelector('[data-security=refresh]').click()");await wait(tab,"!!document.querySelector('[data-security=recovery-key]')",'local recovery key control');assert.equal(keyRequests,0,'Showing the recovery-key control must not request a key');await action(tab,"window.exportProbe=null;document.querySelector('[data-security=recovery-key]').click()");await wait(tab,"!!window.exportProbe",'recovery key download');assert.match(await ui.evaluate(tab,'window.exportProbe.name'),/^seek-recovery-key-/);assert.equal(await ui.evaluate(tab,"fetch(window.exportProbe.href).then(r=>r.json()).then(x=>x.key)"),'recovery-fixture-opaque-key');assert.equal(await ui.evaluate(tab,"document.body.textContent.includes('recovery-fixture-opaque-key')"),false,'Key must not appear in the page or toast');assert.equal(keyRequests,1);backupLocal=false;await action(tab,"document.querySelector('[data-security=refresh]').click()");await wait(tab,"!!document.querySelector('[data-security=backup]')&&!document.querySelector('[data-security=recovery-key]')",'public recovery control hidden again');
  await action(tab,"document.querySelector('[data-view=chat]').click()");
  await ui.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},session);assert.equal(await ui.evaluate(tab,"getComputedStyle(document.querySelector('#buddy-top')).visibility"),'visible');await action(tab,"document.querySelector('#buddy-top').focus()");assert.equal(await ui.evaluate(tab,"document.activeElement.id"),'buddy-top');await action(tab,"document.querySelector('#buddy-top').click()");assert.equal(await ui.evaluate(tab,"document.querySelector('#agent-panel').getAttribute('aria-modal')"),'true');assert.equal(await ui.evaluate(tab,"document.querySelector('.workspace').inert"),true);await ui.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},session);await ui.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},session);await new Promise(resolve=>setTimeout(resolve,60));assert.equal(await ui.evaluate(tab,"document.querySelector('.workspace').inert"),false);assert.equal(await ui.evaluate(tab,"document.activeElement.id"),'buddy-top','Escape must return focus after inert background is released');await action(tab,"document.querySelector('#buddy-top').click();document.querySelector('#ap-close').click()");assert.equal(await ui.evaluate(tab,"document.activeElement.id"),'buddy-top');
  await action(tab,"document.querySelector('#mobile-more').click()");assert.equal(await ui.evaluate(tab,"document.querySelector('#menu').getAttribute('aria-expanded')"),'true');assert.equal(await ui.evaluate(tab,"document.querySelector('.workspace').inert"),true);await ui.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'},session);assert.equal(await ui.evaluate(tab,"document.querySelector('.workspace').inert"),false);assert.equal(await ui.evaluate(tab,"document.activeElement.id"),'menu');assert.equal(await ui.evaluate(tab,"getComputedStyle(document.querySelector('#workspace-nav')).visibility"),'hidden');
  assert.equal(await ui.evaluate(tab,'document.documentElement.scrollWidth<=innerWidth'),true,'mobile overflow');
  const output=process.env.SEEK_TEST_OUTPUT;if(output){await mkdir(output,{recursive:true});await writeFile(join(output,'product-mobile.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));await ui.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false},session);await action(tab,"document.querySelector('[data-view=files]').click()");await writeFile(join(output,'product-library.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));await action(tab,"document.querySelector('[data-view=workflows]').click()");await writeFile(join(output,'product-workflows.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));await action(tab,"document.querySelector('[data-select=beta]').click()");await wait(tab,"!!document.querySelector('.work-summary progress')",'progress screenshot');await writeFile(join(output,'product-progress.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));await action(tab,"document.querySelector('#new-task').click()");await writeFile(join(output,'product-welcome.png'),Buffer.from(await ui.screenshot(tab,{format:'png'}),'base64'));}
  await ui.send('Emulation.setDeviceMetricsOverride',{width:320,height:740,deviceScaleFactor:1,mobile:true},session);assert.equal(await ui.evaluate(tab,'document.documentElement.scrollWidth<=innerWidth'),true,'small phone overflow');
  Object.assign(tasks[1],{status:'complete',completedAt:now+5000,updatedAt:Date.now()+1});updates.refresh();await action(tab,"document.querySelector('[data-select=beta]').click()");await wait(tab,"document.querySelector('.work-done-label')?.textContent==='Finished'&&!document.querySelector('.work-summary')",'completion overrides last working step');assert.equal(await ui.evaluate(tab,"!!document.querySelector('.work-summary progress')"),false);await wait(tab,"document.querySelector('[data-work-elapsed]')?.textContent==='5s elapsed'",'completed elapsed time');await new Promise(resolve=>setTimeout(resolve,1100));assert.equal(await ui.evaluate(tab,"document.querySelector('[data-work-elapsed]').textContent"),'5s elapsed','Completed elapsed time must stay frozen');
  await ui.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false},session);
  await action(tab,"document.querySelector('[data-view=files]').click()");await wait(tab,"!!document.querySelector('#library-date')",'library date filter');
  await action(tab,"{const q=document.querySelector('#library-search');q.value='hidden phrase';q.dispatchEvent(new Event('input',{bubbles:true}))}");await wait(tab,"document.querySelector('.library-match')?.textContent.includes('<hidden phrase>')",'content match excerpt');assert.equal(await ui.evaluate(tab,"document.querySelectorAll('.library-card').length"),1);
  await action(tab,"{const q=document.querySelector('#library-search');q.value='';q.dispatchEvent(new Event('input',{bubbles:true}));const d=document.querySelector('#library-date');d.value='today';d.dispatchEvent(new Event('change',{bubbles:true}))}");await wait(tab,"document.querySelector('#library-date').value==='today'&&!document.querySelector('.library-searching')",'date filter applied');
  const branchBodies=bodies.length;await action(tab,"document.querySelector('[data-view=chat]').click();document.querySelector('[data-select=alpha]').click()");await wait(tab,"!!document.querySelector('[data-edit-message]')",'edit control on your request');
  await action(tab,"document.querySelector('[data-edit-message]').click()");await wait(tab,"!!document.querySelector('.msg-edit textarea')",'inline editor');assert.equal(await ui.evaluate(tab,"document.activeElement.matches('.msg-edit textarea')"),true,'editor takes focus');
  await action(tab,"{const a=document.querySelector('.msg-edit textarea');a.value='Create a shorter report';a.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.msg-edit').requestSubmit()}");await wait(tab,"!!document.querySelector('.conversation')&&!document.querySelector('.msg-edit')",'branch sent');
  const branch=bodies.slice(branchBodies).find(b=>b.branchFrom);assert.deepEqual([branch?.objective,branch?.branchFrom],['Create a shorter report',{taskId:'alpha',messageIndex:0}],'edit sends a branch of the selected request');
  await action(tab,"document.querySelector('#new-task').click()");await wait(tab,"!!document.querySelector('#mode option[value=\"desktop:fixture-mac\"]')",'remote computer choice');
  await action(tab,"document.querySelector('#mode').value='desktop:fixture-mac';document.querySelector('#prompt').value='Use Notes on the selected Mac';document.querySelector('#composer').requestSubmit()");await wait(tab,"!!document.querySelector('.conversation')",'remote task sent');assert.equal(bodies.find(b=>b.objective==='Use Notes on the selected Mac')?.desktopDeviceId,'fixture-mac');
  await action(tab,"document.querySelector('#new-task').click();document.querySelector('#mode').value='browser';document.querySelector('#prompt').value='Find a fixture in Seek browser';document.querySelector('#composer').requestSubmit()");await wait(tab,"!!document.querySelector('.conversation')",'browser task sent');assert.equal(bodies.find(b=>b.objective==='Find a fixture in Seek browser')?.executionMode,'browser');
  assert.deepEqual(errors,[],'no runtime exceptions');
 }finally{for(const stream of streams)stream.end();await ui.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
});
