import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WorkEngine,modelWorkBlocksImages} from '../lib/work-server.js';
import {WorkflowService} from '../lib/work-workflow-service.js';
import {FakeHarness} from './fake-harness.mjs';
import {WorkDatabase} from '../lib/work-database.js';
import {CapabilityRegistry,objectSchema} from '../lib/work-capabilities.js';
import {validateRecipe} from '../lib/work-workflows.js';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'seek-wf-engine-')),harness=new FakeHarness(),engine=new WorkEngine(harness,root,{warn:console.warn},()=>null,{storage:new WorkDatabase(root)});await engine.init();engine.workflowEnabled=true;engine.workflows=new WorkflowService(root,{engine,calendar:{zone:'UTC',range:()=>({events:[],todos:[]})}});return {root,harness,engine,close:async()=>{await engine.workflows.close();await engine.persistence.close();}};}
async function settled(e){await e.tick();await Promise.all([...e.workflowFlights.values()]);}
test('CPU task has durable history, artifact and verified completion without model or helpers',async()=>{const f=await fixture();try{let helpers=0;f.engine.titler=()=>helpers++;f.engine.suggester=()=>helpers++;const t=await f.engine.create({objective:'Calculate calendar availability without a model inference session',workflow:{id:'calendar_availability',input:{from:'2026-10-09T09:00',to:'2026-10-09T17:00'}}});await settled(f.engine);assert.equal(t.status,'complete');assert.equal(t.resultEvidence.status,'verified');assert.equal(t.artifacts.length,1);assert.match(t.result,/480 minutes/);assert.equal(f.harness.calls.length,0);assert.equal(helpers,0);assert.equal(modelWorkBlocksImages(f.engine),false);}finally{await f.close();}});
test('explicit CPU runs start immediately without waiting for the ordinary task tick',async()=>{const f=await fixture();try{const t=await f.engine.create({objective:'Estimate groceries',workflow:{id:'grocery_cart_plan',input:{items:[],catalog:[]}}});assert.equal(t.status,'running');await Promise.all([...f.engine.workflowFlights.values()]);assert.equal(t.status,'complete');assert.equal(f.harness.calls.length,0);}finally{await f.close();}});
test('grocery exceptions become a persistent decision and can continue through normal chat',async()=>{const f=await fixture();try{const t=await f.engine.create({objective:'Plan groceries',workflow:{id:'grocery_cart_plan',input:{items:[{productId:'milk',quantity:1}],catalog:[]}}});await settled(f.engine);assert.equal(t.status,'waiting');assert.ok(t.question.choices.includes('Continue in chat'));await f.engine.control(t.id,'reply','Choose a different milk');assert.equal(t.workflow,null);assert.match(t.pendingReply,/workflow-result/);await f.engine.tick();assert.equal(f.harness.calls.filter(c=>c[0]==='create'&&Object.hasOwn(c[1],'cwd')).length,1);}finally{await f.close();}});
test('scheduled runs pin recipe/input and do not create inference sessions',async()=>{const f=await fixture();try{const t=await f.engine.create({objective:'Plan groceries',repeatHours:1,workflow:{id:'grocery_cart_plan',input:{items:[],catalog:[]}}});await settled(f.engine);await f.engine.tick();const next=f.engine.store.tasks.find(x=>x.id!==t.id);assert.equal(next.status,'scheduled');assert.equal(next.workflow.version,1);assert.equal(f.harness.calls.length,0);}finally{await f.close();}});
test('migration and restart preserve completed runs and existing task history',async()=>{const f=await fixture();try{const t=await f.engine.create({objective:'Estimate cart',workflow:{id:'grocery_cart_plan',input:{items:[],catalog:[]}},requestId:'stable'});await settled(f.engine);const count=f.engine.store.tasks.length;assert.equal((await f.engine.create({objective:'Estimate cart',workflow:{id:'grocery_cart_plan',input:{items:[],catalog:[]}},requestId:'stable'})).id,t.id);assert.equal(f.engine.store.tasks.length,count);await f.engine.persistence.close();const e=new WorkEngine(f.harness,f.root,console,()=>null,{storage:new WorkDatabase(f.root)});await e.init();assert.equal(e.task(t.id).status,'complete');assert.equal(e.task(t.id).workflow.runId,t.workflow.runId);await e.persistence.close();}finally{await f.engine.workflows.close();}});
test('unknown ordinary tasks still take their existing agent path with no workflow classifier',async()=>{const f=await fixture();try{const t=await f.engine.create({objective:'Write an original poem about autumn',mode:'chat'});await f.engine.tick();assert.equal(t.workflow,undefined);assert.equal(f.harness.prompts.length,1);}finally{await f.close();}});
test('a read workflow cannot complete a calendar mutation or a requested missing file',async()=>{const f=await fixture();try{
 await assert.rejects(f.engine.create({objective:'Move my dentist appointment to Friday',workflow:{id:'calendar_availability',input:{from:'2026-10-09T09:00',to:'2026-10-09T17:00'}}}),/whole request/);
 const t=await f.engine.create({objective:'Calculate groceries and save the report to groceries.md',workflow:{id:'grocery_cart_plan',input:{items:[],catalog:[]}}});await settled(f.engine);assert.equal(t.status,'attention');assert.equal(t.resultEvidence.status,'needs-verification');
 }finally{await f.close();}});
test('shutdown waits for task checkpoint writes before closing workflow and task databases',async()=>{
 const f=await fixture();await f.engine.workflows.close();let started;
 const seen=new Promise(r=>started=r),empty=objectSchema({},[]),registry=new CapabilityRegistry().register({name:'fixture.slow',version:1,effect:'pure',input:empty,output:empty,execute:async(_a,c)=>{started();await new Promise(resolve=>c.signal.addEventListener('abort',resolve,{once:true}));return {};},verify:()=>true});
 f.engine.workflows=new WorkflowService(f.root,{engine:f.engine,registry});const recipe={id:'slow_fixture',version:1,title:'Slow fixture',input:empty,steps:[{id:'wait',capability:'fixture.slow',version:1,input:{}}],result:'wait'};f.engine.workflows.store.put(validateRecipe(recipe,registry));
 const t=await f.engine.create({objective:'Run slow fixture',workflow:{id:recipe.id,input:{}}});await f.engine.tick();await seen;await f.close();assert.equal(t.status,'stopped');assert.equal(f.engine.workflowFlights.size,0);
});
test('candidate recipes require varied examples and remain tested until enabled',async()=>{const f=await fixture();try{const schema={type:'object',properties:{values:{type:'array',items:{type:'integer'},maxItems:50}},required:['values'],additionalProperties:false},r={id:'my_sum',version:1,title:'My sum',input:schema,steps:[{id:'sum',capability:'data.sum_cents',version:1,input:{values:{$ref:'input.values'}}}],result:'sum'},task={id:'candidate',status:'running'};
 await assert.rejects(f.engine.workflows.candidate(r,[{input:{values:[1]},expected:{totalCents:1}}],task),/two/);
 const d=await f.engine.workflows.candidate(r,[{input:{values:[1,2]},expected:{totalCents:3}},{input:{values:[-2,3]},expected:{totalCents:1}}],task);assert.equal(d.state,'tested');assert.throws(()=>f.engine.workflows.select(r.id,1),/disabled/);f.engine.workflows.store.setState(r.id,1,'enabled');assert.equal((await f.engine.workflows.toolRun(task,{id:r.id,input:{values:[4,5]}})).result.totalCents,9);
 }finally{await f.close();}});
