# Serve the local models for the DeepSeek Harness via llama.cpp ROUTER mode.
#
# All paths, ports and limits come from seek.config.ps1 -- edit that, not this.
#
# WHY A ROUTER: llama-server can host several models and keep only --models-max
# of them resident, evicting the least-recently-used one. With --models-max 1
# that means whichever model you pick in the harness owns the WHOLE GPU, so a
# second model no longer has to run ngl=0 on the CPU. Measured on a 24 GB 3090:
# Gemma 4 26B-A4B went from 12.6 t/s (CPU-only, because Qwen held all 24 GB)
# to 196 t/s once it could take the GPU. A full swap costs ~11 s.
#
# The router is configured by an INI file, generated here so seek.config.ps1
# stays the single source of truth. In that file a SECTION NAME is the id
# clients send in the "model" field, so it must match `id:` in settings.yaml.

param(
  [string]$ConfigPath = $(if ($env:SEEK_CONFIG) { $env:SEEK_CONFIG } else { "$env:USERPROFILE\.dsh\seek.config.ps1" })
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $ConfigPath)) {
  throw "Config not found at $ConfigPath. Run install.ps1, or pass -ConfigPath."
}
. $ConfigPath

$exe = Join-Path $LlamaDir "llama-server.exe"
$ini = Join-Path $LlamaDir "models.ini"
$log = Join-Path $LlamaDir "router.log"

if (-not (Test-Path $exe))       { throw "llama-server.exe not found at $exe" }
if (-not (Test-Path $ModelPath)) { throw "Model not found at $ModelPath" }

# --- build models.ini --------------------------------------------------------
#
# Unlike Start-Process -ArgumentList, INI values are read verbatim, so a value
# containing spaces needs NO embedded quotes. (The old launcher had to wrap
# --reasoning-budget-message in literal quotes or argv splitting broke it.)

$lines = @(
  "; GENERATED by serve-router.ps1 from seek.config.ps1 -- edits here are lost."
  "; Section name = the id clients send as `"model`". Must match settings.yaml."
  ""
  "[*]"
  "c = $ContextSize"
  "cache-type-k = q8_0"
  "cache-type-v = q8_0"
  "flash-attn = on"          # required for a quantized V cache
  "jinja = true"             # chat template -> tool calling + reasoning split
  "parallel = 1"             # >1 eats the speculative-decoding win
  ""
  "[$ModelAlias]"
  "model = $ModelPath"
  "ngl = $GpuLayers"
  # Qwen3.8 ships MTP (nextn) heads inside the GGUF. Without this llama.cpp
  # loads them and prints "unused tensor blk.*.nextn.* -- ignoring", costing
  # ~half the generation speed: measured 36.0 -> 53.8 t/s (1.49x) for +637 MB.
  "spec-type = draft-mtp"
  "spec-draft-n-max = 2"     # 24 GB cards peak at 2; 3 was measurably WORSE
  # Server-side floor for requests that name no effort (session titling, and
  # anything bypassing the harness). Qwen3.8's template defaults to xhigh:
  # measured 2214 completion tokens vs 575 at medium for the same answer.
  "reasoning-effort = $ReasoningEffort"
  # HARD cap. reasoning_effort alone is a prompt suggestion that holds on easy
  # turns and is IGNORED on hard ones (measured 22,747 completion tokens at
  # effort=low on an open-ended prompt). This flag is the enforcement.
  "reasoning-budget = $ReasoningBudget"
  "reasoning-budget-message = Reasoning budget reached. Commit to the best option so far and immediately emit the answer or the next tool call."
)

# --- optional second model ---------------------------------------------------
if ($Model2Path -and (Test-Path $Model2Path)) {
  $m2ngl = if ($Model2GpuLayers) { $Model2GpuLayers } else { $GpuLayers }
  $lines += @(
    ""
    "[$Model2Alias]"
    "model = $Model2Path"
    "ngl = $m2ngl"
  )
  # A separate draft GGUF, for models whose MTP head ships as its own file
  # rather than inside the main weights (Gemma 4 is one).
  if ($Model2Draft -and (Test-Path $Model2Draft)) {
    $lines += "model-draft = $Model2Draft"
    $lines += "spec-type = draft-mtp"
    $lines += "spec-draft-n-max = $(if ($Model2SpecNMax) { $Model2SpecNMax } else { 4 })"
  }
} elseif ($Model2Path) {
  Write-Host "WARN: `$Model2Path is set but missing ($Model2Path) - serving one model only"
}

# NOT Set-Content -Encoding UTF8: under Windows PowerShell 5.1 that writes a
# BOM, which would land on the first line. It is harmless today only because
# line 1 is a comment -- if a section header ever ended up first, the INI parser
# would choke on it. WriteAllLines with UTF8Encoding($false) is BOM-free on both
# 5.1 and 7.
[System.IO.File]::WriteAllLines($ini, $lines, (New-Object System.Text.UTF8Encoding($false)))

$svrArgs = @(
  "--models-preset", $ini
  "--models-max", "1"        # one resident model -> it gets the whole GPU
  "--host", "127.0.0.1"
  "--port", "$LlamaPort"
)

Start-Process -FilePath $exe -ArgumentList $svrArgs `
  -RedirectStandardOutput $log -RedirectStandardError "$log.err" `
  -WindowStyle Hidden

Write-Host "llama.cpp router starting on http://127.0.0.1:$LlamaPort (log: $log, presets: $ini)"
